(function(){
  'use strict';
  var recruiters=[];
  function byId(id){return document.getElementById(id)}
  function initials(name){return String(name||'').split(/\s+/).filter(Boolean).slice(0,2).map(function(part){return part.charAt(0).toUpperCase()}).join('')||'R'}
  function goToJobs(name){if(typeof window.showPage==='function')window.showPage('jobs',byId('navJobs'));setTimeout(function(){var select=byId('jobsRecruiterFilter');if(select){select.value=name;select.dispatchEvent(new Event('change',{bubbles:true}))}},0)}
  function share(name){try{sessionStorage.setItem('atsrs_recruiter_share_target',JSON.stringify({name:name}))}catch(_error){}if(typeof window.showPage==='function')window.showPage('profile',byId('navProfile'));setTimeout(function(){var sharing=byId('profileTabSharingBtn');if(sharing)sharing.click();var edit=byId('profileSharingEditBtn');if(edit)edit.click();var recipient=document.querySelector('input[name="profileSharingAudience"][value="recipient"]');if(recipient&&!recipient.disabled){recipient.checked=true;recipient.dispatchEvent(new Event('change',{bubbles:true}))}var status=byId('profileSharingCreateStatus');if(status)status.textContent='Create a secure link for '+name+', then copy it to the recruiter’s verified contact route.'},0)}
  function action(label,icon,handler){var button=document.createElement('button');button.type='button';button.innerHTML='<i class="ph ph-'+icon+'" aria-hidden="true"></i><span>'+label+'</span>';button.addEventListener('click',handler);return button}
  function card(name){var article=document.createElement('article');article.className='employer-card';article.dataset.recruiterName=name;var head=document.createElement('div');head.className='employer-card-head';var mark=document.createElement('div');mark.className='employer-mark';mark.textContent=initials(name);var copy=document.createElement('div');copy.className='employer-card-copy';var source=document.createElement('span');source.className='employer-source';source.innerHTML='<i class="ph ph-briefcase" aria-hidden="true"></i> Active in JobSearch';var title=document.createElement('h4');title.textContent=name;var summary=document.createElement('p');summary.textContent='Recruiter listed on one or more published ATSRS vacancies.';copy.append(source,title,summary);head.append(mark,copy);var actions=document.createElement('div');actions.className='employer-actions';actions.append(action('View jobs & contact','address-book',function(){goToJobs(name)}),action('Share my profile','share-network',function(){share(name)}));article.append(head,actions);return article}
  function sync(){var select=byId('jobsRecruiterFilter');if(!select)return;recruiters=Array.from(select.options).map(function(option){return String(option.value||'').trim()}).filter(Boolean).filter(function(name,index,list){return list.indexOf(name)===index}).sort(function(a,b){return a.localeCompare(b)});render()}
  function render(){var grid=byId('recruitersGrid');if(!grid)return;var query=String(byId('recruitersSearch').value||'').trim().toLowerCase();var visible=recruiters.filter(function(name){return !query||name.toLowerCase().indexOf(query)>=0});grid.textContent='';visible.forEach(function(name){grid.appendChild(card(name))});byId('recruitersEmpty').classList.toggle('hidden',visible.length>0);byId('recruitersVisibleCount').textContent=visible.length+' of '+recruiters.length+' recruiters'}
  function install(){if(!byId('recruitersPage'))return;byId('recruitersSearch').addEventListener('input',render);byId('recruitersClearFilters').addEventListener('click',function(){byId('recruitersSearch').value='';render()});sync();var select=byId('jobsRecruiterFilter');if(select)new MutationObserver(sync).observe(select,{childList:true});window.addEventListener('atsrs:resume',sync)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
