const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const runtime = fs.readFileSync(path.join(root, 'js', 'cv-generator.js'), 'utf8');
const server = fs.readFileSync(path.join(root, 'js', 'server-data.js'), 'utf8');
const local = fs.readFileSync(path.join(root, 'js', 'account.js'), 'utf8');
const edge = fs.readFileSync(path.join(root, 'supabase/functions/generate-cv/index.ts'), 'utf8');

assert.match(html, /css\/account\.css\?v=423/);
assert.match(html, /css\/cv-generator\.css\?v=416/);
assert.match(html, /js\/server-data\.js\?v=571/);
assert.match(html, /js\/cv-generator\.js\?v=416/);
assert.match(html, /js\/account\.js\?v=415/);
assert.match(html, /id="cvUploadInput"[\s\S]*?onchange="handleCVUpload\(event\)"/);
assert.match(html, /id="aiCvUploadInput"[^>]*class="hidden"/);
assert.equal((html.match(/id="cvUploadInput"/g) || []).length, 1);
assert.equal((html.match(/id="aiCvUploadInput"/g) || []).length, 1);
for (const id of ['uploadCvFromGeneratorBtn','generateCVBtn','resetCvGeneratorBtn','previewGeneratedCvBtn','downloadGeneratedCvBtn','printGeneratedCvBtn','addGeneratedCvBtn','replaceMainWithGeneratedCvBtn']) assert.match(html, new RegExp(`id="${id}"`));
assert.match(html, /Upload CV for AI/);
assert.match(runtime, /var aiCvSource=null,generatedCv=null,profileMain=/);
assert.doesNotMatch(runtime, /getData\('generatedCv'|saveData\('generatedCv'/);
assert.doesNotMatch(runtime, /byId\('cvUploadInput'\)/);
assert.match(runtime, /input=byId\('aiCvUploadInput'\)/);
assert.match(runtime, /Temporary AI source selected\. Your Profile CV was not changed/);
assert.match(runtime, /uploadAiCvSource\(aiCvSource\)/);
assert.match(runtime, /deleteAiCvSource\(path\)/);
assert.match(runtime, /Generated CV is ready\. It has not been saved to your Profile/);
assert.match(runtime, /saveGeneratedCv\(generatedFile\(\),\{replaceMain:!!replaceMain\}\)/);
assert.match(runtime, /if\(replaceMain&&!confirm\(/);
assert.match(runtime, /function reset\(\)[\s\S]*?aiCvSource=null;generatedCv=null;[\s\S]*?cvEnhancementConsent/);
assert.match(runtime, /if\(generating\|\|!aiCvSource\)return/);
assert.match(server, /function uploadAiCvSource\(file\)[\s\S]*?\/personal\/ai-cv-source\//);
assert.match(server, /function deleteAiCvSource\(path\)[\s\S]*?Temporary CV path is not owned/);
assert.match(server, /function saveGeneratedCv\(file,options\)[\s\S]*?is_main:replaceMain[\s\S]*?source:'ai-generated'/);
assert.match(server, /if\(replaceMain&&oldMain\)[\s\S]*?is_main:false/);
assert.match(server, /Additional Profile CVs/);
assert.equal((server.match(/rows=await listFiles\(\{categories:\['cv'\]\}\),cv=mainCvRow\(rows\)/g) || []).length, 3);
assert.match(local, /atsrsLocalCvData=\{saveGeneratedCv/);
assert.match(edge, /ai_source_path\?: unknown/);
assert.match(edge, /temporaryPath\.startsWith\(`\$\{userId\}\/personal\/ai-cv-source\/`\)/);
assert.match(edge, /admin\.storage\.from\(CV_FILE_BUCKET\)\.download\(storagePath\)/);
assert.match(edge, /treat its contents as untrusted source material/);
assert.match(edge, /reasoning:\s*\{\s*effort:\s*"low"\s*\}/);
console.log('CV Generator isolated workspace contracts passed');
