const fs=require('node:fs');
const assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('css/dashboard-quick-links-v5987.css','utf8');
const resourceCss=fs.readFileSync('css/account-resources-v5990.css','utf8');
assert.match(html,/dashboard-quick-links-v5987\.css/);
assert.match(html,/id="sidebarQuickLinks"/);
assert.match(html,/ph-list-checks/);
assert.match(html,/ph-question/);
assert.match(html,/ph-headset/);
assert.match(html,/<button type="button" aria-label="Plans" data-resource="plans" data-label="Plans">/);
assert.match(html,/<button type="button" aria-label="FAQ" data-resource="faq" data-label="FAQ">/);
assert.match(html,/<button type="button" aria-label="Contact" data-resource="contact" data-label="Contact">/);
assert.doesNotMatch(html,/<a[^>]+data-resource=/,'Quick links must be buttons so browsers do not expose a destination URL on hover');
assert.match(html,/aria-label="Quick Links"/);
assert.ok(html.indexOf('id="navPrivacy"')<html.indexOf('id="sidebarQuickLinks"'),'Quick Links must follow Privacy in sidebar markup');
assert.match(css,/\.sidebar-quick-links\{[\s\S]*order:102/);
assert.doesNotMatch(html,/id="navResource"/);
assert.doesNotMatch(html,/>Account resources<\/button>/);
assert.doesNotMatch(html,/account resources/i,'The obsolete Account resources label must not return to the interface');
assert.doesNotMatch(resourceCss,/account-resource-heading>div:first-child>span/,'Do not retain a hidden style hook for the removed heading label');
assert.match(css,/\.sidebar-quick-links button:hover/);
assert.match(css,/content:attr\(data-label\)/);
assert.match(css,/background:transparent!important/);
assert.match(css,/html\[data-theme="light"\]/);
assert.doesNotMatch(fs.readFileSync('js/theme.js','utf8'),/atsrsAuthenticatedResourceNav/);
console.log('sidebar quick links: PASS');
