const fs=require('node:fs');
const assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('css/dashboard-quick-links-v5987.css','utf8');
const resourceCss=fs.readFileSync('css/account-resources-v5990.css','utf8');
assert.match(html,/dashboard-quick-links-v5987\.css/);
assert.match(html,/account-resources-v5990\.css\?v=5993/);
assert.match(html,/id="sidebarQuickLinks"/);
assert.match(html,/ph-credit-card/);
assert.match(html,/ph-question/);
assert.match(html,/ph-headset/);
assert.match(html,/<span role="button" tabindex="0" aria-label="Support" data-resource="contact" data-label="Support">/);
assert.match(html,/<span role="button" tabindex="0" aria-label="FAQ" data-resource="faq" data-label="FAQ">/);
assert.match(html,/<span role="button" tabindex="0" aria-label="Plans and pricing" data-resource="plans" data-label="Plans &amp; Pricing">/);
assert.ok(html.indexOf('data-label="Support"')<html.indexOf('data-label="FAQ"'),'Support must be the left quick link');
assert.ok(html.indexOf('data-label="FAQ"')<html.indexOf('data-label="Plans &amp; Pricing"'),'Plans & Pricing must be the right quick link');
assert.doesNotMatch(html,/<(?:a|button)[^>]+data-resource=/,'Quick links must avoid both anchor URL previews and global sidebar button sizing');
assert.match(html,/aria-label="Quick Links"/);
assert.ok(html.indexOf('id="navPrivacy"')<html.indexOf('id="sidebarQuickLinks"'),'Quick Links must follow Privacy in sidebar markup');
assert.match(css,/\.sidebar-quick-links\{[\s\S]*order:102/);
assert.doesNotMatch(html,/id="navResource"/);
assert.doesNotMatch(html,/>Account resources<\/button>/);
assert.doesNotMatch(html,/account resources/i,'The obsolete Account resources label must not return to the interface');
assert.doesNotMatch(resourceCss,/account-resource-heading>div:first-child>span/,'Do not retain a hidden style hook for the removed heading label');
assert.match(resourceCss,/account-resource-content\[data-resource="plans"\]\{height:auto;overflow:visible\}/,'Plans must use the page scrollbar instead of a nested scroll panel');
assert.match(resourceCss,/\.account-resource-frame-shell\{position:relative;min-height:max\(480px,calc\(100vh - 280px\)\)/,'Resources must not collapse before their content is identified and loaded');
assert.match(css,/\.sidebar-quick-links \[role="button"\]:hover/);
assert.match(css,/content:attr\(data-label\)/);
assert.match(css,/background:transparent!important/);
assert.match(css,/html\[data-theme="dark"\][\s\S]*\.sidebar-quick-links \[role="button"\]:hover[\s\S]*background:transparent!important/);
assert.match(fs.readFileSync('js/account-resources-v5990.js','utf8'),/event\.key!=='Enter'&&event\.key!==' '/);
assert.match(css,/html\[data-theme="light"\]/);
assert.doesNotMatch(fs.readFileSync('js/theme.js','utf8'),/atsrsAuthenticatedResourceNav/);
console.log('sidebar quick links: PASS');
