const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const js = fs.readFileSync(path.join(root, 'js', 'admin-overview.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'css', 'developer-registration-v5895.css'), 'utf8');
const migration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260828004100_include_incomplete_developer_registrations.sql'), 'utf8');

assert.match(index, /id="navDeveloper"[^>]+hidden/);
assert.match(index, /id="developerPage"/);
assert.match(index, /id="developerRegistrationRows"/);
assert.ok(index.indexOf('id="adminOverviewPanel"') > index.indexOf('id="developerPage"'));
assert.ok(index.indexOf('id="adminOverviewPanel"') > index.indexOf('class="developer-registrations-head"'));
assert.doesNotMatch(index.slice(index.indexOf('id="dashboardPage"')), /id="adminOverviewPanel"/);
assert.match(js, /atsrs_get_developer_access_windows/);
assert.match(js, /formatRemaining\(left\)/);
assert.match(js, /row.uploaded_file_count/);
assert.match(js, /item.append\(email, registered, documents, status, remaining\)/);
assert.match(index, /role="columnheader">Documents<\/span>/);
assert.match(css, /developer-document-count/);
assert.match(css, /scrollbar-color:#3b82f6 #edf2fa/);
assert.match(css, /html\[data-theme="light"\] #developerPage \.admin-overview-stat strong/);
const countsMigration=fs.readFileSync(path.join(root,'supabase/migrations/20260902223611_developer_uploaded_file_counts.sql'),'utf8');
assert.match(countsMigration,/perform 1 from public\.atsrs_get_developer_registrations\(\)/);
assert.match(countsMigration,/coalesce\(f.file_count,0\)/);
assert.match(countsMigration,/select user_id,count\(\*\) as file_count from public\.atsrs_files group by user_id/);
assert.match(js, /developerNav\.classList\.remove\('hidden'\)/);
assert.match(js, /get\('route'\) === 'developer'/);
assert.match(js, /window\.showPage\('developer', developerNav\)/);
assert.match(js, /stabilizeAuthorizedDeveloperRoute/);
assert.match(js, /section\.classList\.toggle\('hidden', section !== developerPage\)/);
assert.match(js, /observeAuthorizedDeveloperRoute/);
assert.match(js, /developerRouteObserver\.observe\(main/);
assert.match(css, /\.developer-registration-rows\{max-height:480px;overflow-y:auto/);
assert.match(css, /grid-template-columns:minmax\(180px,auto\) minmax\(460px,1fr\) auto/);
assert.match(css, /\.developer-page \.developer-admin-overview\{[\s\S]*?position:static!important/);
assert.match(css, /#app \.nav #navDeveloper\.hidden\{display:none!important\}/);
assert.match(migration, /ATSRS_ADMIN_REQUIRED/);
assert.match(migration, /subscription\.trial_ends_at - now\(\)/);
assert.match(migration, /order by auth_user\.created_at desc/);

console.log('developer-registration-monitor: PASS');
