const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const js = fs.readFileSync('js/recruiters.js', 'utf8');
const html = fs.readFileSync('index.html', 'utf8');
const css = fs.readFileSync('css/company-directory-v6034.css', 'utf8');
const reset = js.match(/  function resetFilters\(activeOnly, scrollToCards\) \{[\s\S]*?\n  \}/)[0];
const fields = Object.fromEntries(['recruitersSearch', 'recruitersCompany', 'recruitersVacancies', 'recruitersSort'].map(id => [id, {value: 'filtered'}]));
let renders = 0, scrolls = 0;
fields.recruitersGrid = {scrollIntoView() { scrolls++; }};
const context = {byId: id => fields[id], recruiterPage: 3, render() { renders++; }};
vm.createContext(context);
vm.runInContext(reset + '\nresetFilters(false, false);', context);
assert.equal(scrolls, 0, 'Clear filters must not move the viewport');
assert.equal(renders, 1);
assert.equal(context.recruiterPage, 1);
assert.equal(fields.recruitersSearch.value, '');
assert.equal(fields.recruitersCompany.value, '');
assert.equal(fields.recruitersSort.value, 'name');
vm.runInContext('resetFilters(true, true);', context);
assert.equal(scrolls, 1, 'Hero actions should still take users to results');
assert.equal(fields.recruitersVacancies.value, 'active');
assert.match(js, /byId\("recruitersClearFilters"\)[^\n]*resetFilters\(false, false\)/);
assert.match(css, /\.company-hero-light\{display:none/);
assert.match(css, /html\[data-theme="light"\][^{]*\.company-hero-light-wide\{display:block/);
assert.match(css, /\.company-light-lines\{filter:invert\(1\) hue-rotate\(290deg\)/);
assert.match(css, /\.company-light-brands\{filter:invert\(1\) hue-rotate\(180deg\)/);
assert.equal((html.match(/<clipPath id="company-(?:wide|narrow)-brand-marks">/g) || []).length, 2);
console.log('Directory light palette and clear-filter scroll regressions passed');
