const assert = require('node:assert/strict');
const fs = require('node:fs');

const html = fs.readFileSync('index.html', 'utf8');
const js = fs.readFileSync('js/employers.js', 'utf8');
const recruitersJs = fs.readFileSync('js/recruiters.js', 'utf8');
const css = fs.readFileSync('css/employers.css', 'utf8');
const recruiterActionCss = fs.readFileSync('css/recruiter-action-emphasis-v5926.css', 'utf8');
const storage = fs.readFileSync('js/storage.js', 'utf8');

const jobs = html.indexOf('id="navJobs"');
const employers = html.indexOf('id="navEmployers"');
const recruiters = html.indexOf('id="navRecruiters"');
const documents = html.indexOf('id="navCertificates"');
assert.ok(jobs >= 0 && recruiters > jobs && employers > recruiters && documents > employers, 'Recruiters and Companies must sit between JobSearch and Documents in Personal navigation');
assert.match(html, /id="navEmployers"[^>]*>Companies</);
assert.match(html, /id="navRecruiters"[^>]*>Recruiters</);
assert.match(html, /id="employersPage"/);
assert.match(html, /id="recruitersPage"/);
assert.match(html, /ATSRS JOBS RECRUITER DIRECTORY/);
assert.match(html, /Find recruiters connected to ATSRS Jobs/);
assert.doesNotMatch(html, /Find ATSRS JobSearch recruiters/);
assert.match(html, /RECRUITERS &amp; COMPANIES/);
assert.match(html, /Explore recruiters with a Personal account/);
assert.match(html, /Explore companies with a Personal account/);
assert.doesNotMatch(html, /id="(?:employers|recruiters)Heading"/, 'Directory pages must not repeat the white page title as a large green heading');
assert.equal((html.match(/class="atsrs-search-control"/g) || []).length, 3, 'All three directory searches use the canonical control');
assert.match(html, /class="atsrs-search-control"[^>]*>[\s\S]*?id="employersSearch"/);
assert.match(html, /class="atsrs-search-control"[^>]*>[\s\S]*?id="recruitersSearch"/);
assert.match(html, /atsrsOpenJobsDirectory\('recruiters',this\)/);
assert.match(html, /atsrsOpenJobsDirectory\('employers',this\)/);
assert.match(html, /js\/employers\.js\?v=33/);
assert.match(html, /js\/recruiters\.js\?v=15/);
assert.match(html, /css\/employers\.css\?v=30/);
assert.match(html, /css\/recruiter-action-emphasis-v5926\.css\?v=5938/);
assert.match(html, /id="recruitersCompany"[^>]*>[\s\S]*?All companies/);
assert.match(html, /id="recruitersSearch"[^>]*placeholder="Recruiter or company"/);
assert.match(html, /id="employersVacancies"[^>]*>[\s\S]*?Active vacancies only/);
assert.match(html, /id="recruitersVacancies"[^>]*>[\s\S]*?Active vacancies only/);
assert.match(html, /id="employersSort"[^>]*>[\s\S]*?Most vacancies/);
assert.match(html, /id="recruitersSort"[^>]*>[\s\S]*?Most vacancies/);
assert.match(html, /js\/storage\.js\?v=601/);
assert.match(html, /js\/shell-polish\.js\?v=5895/);
assert.match(js, /https:\/\/careers\.subsea7\.com/);
assert.match(js, /https:\/\/www\.oceaneering\.com\/careers\//);
assert.match(js, /https:\/\/www\.dof\.com\/vacancies/);
assert.match(js, /https:\/\/www\.fugro\.com\/careers/);
assert.match(js, /https:\/\/leveloffshoreno\.recman\.page\/jobs\?sort=newest/);
assert.match(js, /https:\/\/hpruk\.com\/vacancies\//);
assert.match(js, /Object\.keys\(verified\)\.forEach/);
assert.doesNotMatch(js, /mailto:/, 'The directory must not send unsolicited email');
assert.match(js, /jobsCompanyFilter/);
assert.match(js, /View jobs/);
assert.match(js, /rpc\("atsrs_jobs_facets"\)/);
assert.match(js, /company\.vacancyCount \+= 1/);
assert.match(js, /b\.vacancyCount - a\.vacancyCount/);
assert.doesNotMatch(js, /MutationObserver|atsrs:jobs-nav|refreshDirectoryOptions/, 'Company totals must not depend on JobSearch page timing');
assert.match(js, /sectorLabel\.textContent = data\.sector \|\| "ATSRS company listing"/);
assert.doesNotMatch(js, /Share my profile|atsrs_employer_share_target|profileTabSharingBtn/, 'Companies must not offer profile sharing without a specific recipient');
assert.match(storage, /employers:navEmployers/g);
assert.match(storage, /recruiters:navRecruiters/g);
assert.match(recruitersJs, /View offers on ATSRS/);
assert.match(recruitersJs, /jobsAction\.disabled = true/);
assert.match(recruitersJs, /No active jobs/);
assert.match(recruitersJs, /Share my profile/);
assert.match(recruitersJs, /recruiter\.role_title \|\| "Recruiter"/);
assert.match(recruitersJs, /role_title: "Recruiter"/);
assert.match(recruitersJs, /location: ""/);
assert.doesNotMatch(recruitersJs, /Recruiter listed on one or more published ATSRS vacancies/);
assert.match(recruitersJs, /atsrs_recruiters/);
assert.match(recruitersJs, /rpc\("atsrs_jobs_facets"\)/);
assert.match(recruitersJs, /vacancyCounts\.get\(normalized\(recruiter\.name\)\)/);
assert.match(recruitersJs, /recruiterMap\.has\(key\)/);
assert.doesNotMatch(recruitersJs, /Recruiter on a published ATSRS vacancy/);
assert.match(recruitersJs, /b\.vacancyCount - a\.vacancyCount/);
assert.match(recruitersJs, /All companies \(" \+ recruiters\.length \+ "\)/);
assert.match(recruitersJs, /matchesCompany/);
assert.doesNotMatch(recruitersJs, /MutationObserver|atsrs:jobs-nav|refreshDirectoryOptions/, 'Recruiter totals must not depend on JobSearch page timing');
assert.match(recruitersJs, /LinkedIn profile/);
assert.match(recruitersJs, /Active on published jobs/);
assert.match(recruitersJs, /employer-action-jobs is-active/);
assert.match(recruitersJs, /"LinkedIn profile"/);
assert.match(recruitersJs, /"View offers on ATSRS"/);
assert.match(recruitersJs, /linkedinAction\.disabled = true/);
assert.match(recruitersJs, /nurlan jafarov/);
assert.match(css, /\.employers-grid/);
assert.match(css, /\.employer-card::before/);
assert.match(css, /#employersPage \.employer-sector-label/);
assert.match(css, /\.employer-vacancy-count/);
assert.match(css, /\.employer-card-copy h4[\s\S]*?color: #fff/);
assert.match(css, /html\[data-theme="light"\] \.employer-card-copy h4/);
assert.match(css, /#employersPage,#recruitersPage/);
assert.match(js, /companyLogos\[company\.name\] \|\| ""/);
assert.match(js, /assets\/company-logos\/blueye-robotics\.ico/);
assert.doesNotMatch(js, /new URL\("\/favicon\.ico"/);
assert.match(js, /employer-mark-fallback/);
assert.match(js, /employer-vacancy-panel/);
assert.match(js, /employer-sector-label/);
assert.match(js, /jobsAction\.className = "employer-action-jobs"/);
assert.match(js, /buttonLink\(data\.website, "Website", "arrow-square-out"\)/);
assert.match(js, /buttonLink\(data\.contact, "Contact", "envelope"\)/);
assert.match(js, /unavailableAction\("Website", "arrow-square-out"\)/);
assert.match(js, /unavailableAction\("Careers", "briefcase"\)/);
assert.match(js, /unavailableAction\("Contact", "envelope"\)/);
assert.match(css, /#employersPage \.employer-card \{[\s\S]*?grid-template-columns: 108px minmax\(0, 1fr\) 128px;[\s\S]*?min-height: 270px;/);
assert.match(css, /#employersPage \.employer-logo/);
assert.match(css, /#employersPage \.employer-actions \.employer-action-jobs/);
assert.match(css, /#employersPage \.employer-actions a,[\s\S]*?height: 38px;/);
assert.match(css, /#employersPage \.employer-actions \.employer-action-jobs \{[\s\S]*?justify-self: end;[\s\S]*?width: auto;/);
assert.match(css, /html\[data-theme\] body #app\.app:not\(\.hidden\) #employersPage \.employer-actions \.employer-action-jobs \{[\s\S]*?height: 38px !important;[\s\S]*?border-color: transparent !important;[\s\S]*?background: transparent !important;[\s\S]*?box-shadow: none !important;/);
assert.match(css, /-webkit-text-fill-color:#fff!important/);
assert.match(css, /\.employer-actions button:disabled/);
assert.match(css, /#recruitersPage \.employer-actions \.employer-action-jobs\.is-active/);
assert.match(css, /\.employer-action-jobs\.is-active \{[\s\S]*?background: #090c0b !important;[\s\S]*?color: #48d46b !important;[\s\S]*?box-shadow: none !important;/);
assert.match(css, /\.employer-action-jobs\.is-active:hover,[\s\S]*?background: var\(--atsrs-field-surface\) !important;[\s\S]*?color: var\(--atsrs-field-accent\) !important;/);
assert.doesNotMatch(css, /\.employer-action-jobs\.is-active \{[\s\S]{0,260}?background: #4bdd6d !important;/);
assert.match(css, /\.employer-action-share[\s\S]*?grid-column: 1 \/ -1/);
assert.match(css, /\.employer-action-jobs:disabled[\s\S]*?display: inline-flex/);
assert.match(css, /rgba\(72, 212, 107, \.58\)/);
assert.match(css, /rgba\(37, 99, 235, \.5\)/);
assert.match(css, /#recruitersPage \.employer-vacancy-hint/);
assert.match(recruiterActionCss, /employer-action-share\.is-shared:disabled/);
assert.match(recruiterActionCss, /background: #090c0b !important/);
assert.match(recruiterActionCss, /box-shadow: none !important/);
assert.match(recruiterActionCss, /:not\(:disabled\):hover/);
assert.match(recruiterActionCss, /border-color: var\(--atsrs-field-focus-block-line\) var\(--atsrs-field-focus-inline-line\) !important/);
assert.match(recruiterActionCss, /background: var\(--atsrs-field-surface\) !important/);
assert.match(recruiterActionCss, /box-shadow: var\(--atsrs-field-focus-shadow\) !important/);
assert.doesNotMatch(recruiterActionCss, /background: #(4bdd6d|2563eb)/i);
assert.match(css, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
assert.match(fs.readFileSync('css/shell-polish.css', 'utf8'), /:not\(\.employer-action-jobs\):not\(\.employer-action-share\):not\(\.employer-action-linkedin\)/);
assert.doesNotMatch(css, /employers-search/, 'Legacy directory search styling must stay removed');

console.log('Employers directory contracts passed');
