const assert = require('node:assert/strict');
const fs = require('node:fs');

const html = fs.readFileSync('index.html', 'utf8');
const js = fs.readFileSync('js/employers.js', 'utf8');
const recruitersJs = fs.readFileSync('js/recruiters.js', 'utf8');
const css = fs.readFileSync('css/employers.css', 'utf8');
const storage = fs.readFileSync('js/storage.js', 'utf8');

const jobs = html.indexOf('id="navJobs"');
const employers = html.indexOf('id="navEmployers"');
const recruiters = html.indexOf('id="navRecruiters"');
const documents = html.indexOf('id="navCertificates"');
assert.ok(jobs >= 0 && recruiters > jobs && employers > recruiters && documents > employers, 'Recruiters and Companies must sit between JobSearch and Documents in Personal navigation');
assert.match(html, /id="navEmployers"[^>]*>Companies</);
assert.match(html, /id="navRecruiters"[^>]*>Recruiters</);
assert.match(html, /id="employersPage"/);
assert.match(html, /id="recruitersPage"/);
assert.match(html, /css\/employers\.css\?v=5/);
assert.match(html, /id="employersSearch"[^>]*data-atsrs-no-field-shell="true"/);
assert.match(html, /id="recruitersSearch"[^>]*data-atsrs-no-field-shell="true"/);
assert.equal((html.match(/atsrs:jobs-nav/g) || []).length >= 3, true);
assert.match(html, /js\/employers\.js\?v=4/);
assert.match(html, /js\/recruiters\.js\?v=2/);
assert.match(html, /js\/storage\.js\?v=591/);
assert.match(html, /js\/shell-polish\.js\?v=570/);
assert.match(js, /https:\/\/careers\.subsea7\.com/);
assert.match(js, /https:\/\/www\.oceaneering\.com\/careers\//);
assert.match(js, /https:\/\/www\.dof\.com\/vacancies/);
assert.match(js, /https:\/\/www\.fugro\.com\/careers/);
assert.doesNotMatch(js, /mailto:/, 'The directory must not send unsolicited email');
assert.match(js, /showPage\(["']profile["']/);
assert.match(js, /profileTabSharingBtn/);
assert.match(js, /jobsCompanyFilter/);
assert.match(js, /View jobs/);
assert.match(storage, /employers:navEmployers/g);
assert.match(storage, /recruiters:navRecruiters/g);
assert.match(recruitersJs, /jobsRecruiterFilter/);
assert.match(recruitersJs, /View jobs & contact/);
assert.match(recruitersJs, /Share my profile/);
assert.match(css, /\.employers-grid/);
assert.match(css, /\.employer-card::before/);
assert.match(css, /#recruitersPage \.employers-search-control input:focus/);
assert.match(css, /:is\(#recruitersPage, #employersPage\) \.employers-search-control:focus-within/);

console.log('Employers directory contracts passed');
