const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const js=fs.readFileSync(path.join(root,'js/executive-dashboard-v5858.js'),'utf8');
const css=fs.readFileSync(path.join(root,'css/executive-dashboard-v5858.css'),'utf8');
const harness=fs.readFileSync(path.join(root,'tests/fixtures/executive-dashboard-harness.html'),'utf8');
const responsiveHarness=fs.readFileSync(path.join(root,'tests/fixtures/executive-dashboard-responsive-frame.html'),'utf8');

assert.match(html,/css\/executive-dashboard-v5858\.css/);
assert.match(html,/css\/executive-dashboard-v5858\.css\?v=5873/);
assert.doesNotMatch(html,/id="soloBadge"|DOCUMENT OVERVIEW/);
assert.match(css,/html\[data-theme="dark"\][\s\S]*?#dashboardHeading\{[\s\S]*?color:var\(--atsrs-ref-dark-text,#f8fafc\)!important/);
assert.match(html,/js\/executive-dashboard-v5858\.js\?v=5882/);

assert.match(js,/atsrsExpiryStatus\.summarize/,'Personal current documents must use the shared expiry contract.');
assert.match(js,/atsrsCorporateReporting\.getCompliance/,'Corporate dashboard must reuse the existing compliance source.');
assert.match(js,/atsrs:corporate-compliance/,'Corporate updates must follow the existing reporting event.');
assert.match(js,/if\(!corporate\(\)\)[\s\S]*?ensurePersonalToolsGrid\(stats\)[\s\S]*?loadPersonalStorage/,'Personal Dashboard must place the requested tools directly below the KPI cards.');
assert.match(js,/ensurePersonalDocumentTimeline\(stats\);renderPersonalDocumentTimeline\(\)/,'Personal Dashboard must render the uploaded-document timeline below Quick Actions.');
assert.match(js,/var sourceItems=documents\(\)/,'Document timeline must use the real Personal document register.');
assert.match(js,/atsrsExpiryStatus\.classify/,'Remaining-time bars must use the shared expiry-status contract.');
assert.match(js,/100\/\(1\+result\.days\/90\)/,'Remaining-time bars must grow monotonically as the number of days falls.');
assert.match(js,/dashboardDocumentListRows[\s\S]*?dashboardDocumentBarRows/,'Documents and remaining-time bars must render in separate cards.');
assert.match(js,/documentRows\.addEventListener\('scroll'[\s\S]*?barRows\.addEventListener\('scroll'/,'The two independent cards must synchronize scrolling in both directions.');
assert.match(js,/dashboardDocumentNameSort[\s\S]*?setTimelineSort\('name'\)/,'The document card must expose A-Z and Z-A sorting.');
assert.match(js,/dashboardDocumentDaysSort[\s\S]*?setTimelineSort\('days'\)/,'The expiry card must expose low-to-high and high-to-low day sorting.');
assert.match(js,/var sourceItems=documents\(\),items=sortedTimelineItems\(sourceItems\)/,'Both cards must render from one shared sorted document order.');
assert.match(js,/atsrs_my_personal_entitlements/,'Storage capacity must come from the authenticated plan entitlement.');
assert.match(js,/from\('atsrs_files'\)\.select\('size_bytes'\)/,'Storage usage must sum real authenticated file metadata.');
assert.match(js,/canvas id="dashboardStorageChart"[\s\S]*?dashboardStoragePercent/,'Storage Usage must render a circular chart with its percentage in the centre.');
assert.match(js,/usedBytes\/limitBytes\*100/,'Storage percentage must be calculated from authenticated usage and the entitlement limit.');
assert.match(js,/MutationObserver\(redrawStorageChart\)/,'The circular storage chart must redraw when light or dark theme changes.');
assert.match(js,/MutationObserver[\s\S]*?dashboardVisible\(\)[\s\S]*?sync/,'Dashboard tools must initialize when authenticated routing reveals the page.');
assert.match(js,/beginInitialSync[\s\S]*?setInterval[\s\S]*?attempts>=40/,'Dashboard initialization must tolerate delayed authenticated rendering.');
assert.match(js,/manualPanel\.dataset\.keepOpen='quick-action'[\s\S]*?\},220\)[\s\S]*?delete manualPanel\.dataset\.keepOpen/,'Document Quick Actions must survive the Documents route settling pass before opening their requested mode.');
assert.match(js,/Add Document','ph-file-plus','document'/,'Add Document must use the reference file-add icon and blue tone.');
assert.match(js,/Scan with AI','ph-magic-wand','ai'/,'Scan with AI must use the reference wand icon and amber tone.');
assert.match(js,/Scan with QR','ph-qr-code','qr'/,'Scan with QR must use the reference QR icon and purple tone.');
assert.match(js,/Manual Upload','ph-upload-simple','upload'/,'Manual Upload must use the reference upload icon and green tone.');
assert.match(js,/Manage Profile','ph-users-three','profile'/,'Manage Profile must use the reference group icon and purple tone.');
assert.match(js,/function openProfileWorkspace\(tab\)[\s\S]*?searchParams\.set\('route','profile'\)[\s\S]*?searchParams\.set\('tab',tab\)[\s\S]*?showAccountTab\('general'\)[\s\S]*?showProfileWorkspaceTab\(tab,false\)/,'Profile Quick Actions must share only a target-aware route helper that keeps the new Profile workspace visible.');
assert.match(js,/function openProfileSharing\(\)\{openProfileWorkspace\('sharing'\)\}/,'Share Link must always open the new Profile Sharing workspace.');
assert.match(js,/function openProfilePersonalInformation\(\)\{openProfileWorkspace\('personal'\)\}/,'Manage Profile must always open Personal Information.');
assert.doesNotMatch(js,/openProfileSharing\(\)[\s\S]{0,240}showAccountTab\('sharing'\)/,'Share Link must not activate the hidden legacy account Sharing tab.');
assert.match(js,/Manage Profile','ph-users-three','profile',openProfilePersonalInformation/,'Manage Profile must use its dedicated Personal Information route.');
assert.match(js,/Share Link','ph-link','sharing',openProfileSharing/,'The final Quick Action must expose the existing Share Link workflow.');
assert.match(js,/href="\/pricing\.html#comparison"[\s\S]*?>Manage Storage<\/a>/,'Manage Storage must expose a native link to the Personal plan comparison page.');
assert.doesNotMatch(js,/Checking your Personal storage|Loading\.\.\.|storageMessage\(/,'Storage refresh must not replace the card with a visible loading or error state.');
assert.match(js,/readPersonalStorageSnapshot[\s\S]*?applyPersonalStorageSnapshot/,'Storage must restore the last authenticated snapshot before its background refresh completes.');
assert.match(js,/applyPersonalStorageSnapshot\(snapshot\);writePersonalStorageSnapshot\(activeUser\.id,snapshot\)/,'Fresh storage totals must update the card and its per-user snapshot together.');
assert.doesNotMatch(js,/addPersonalAction\(actions,'Privacy & Sharing'/,'The legacy Privacy & Sharing Quick Action label must be removed.');
assert.match(js,/uploadedAt/,'Personal recent activity must use real upload timestamps.');
assert.match(js,/uploaded_at/,'Corporate recent activity must use real upload timestamps.');
assert.doesNotMatch(js,/Math\.random|faker|mock data|12\.4|20 GB/i,'Dashboard must not fabricate production data.');
assert.doesNotMatch(js,/fetch\(/,'Dashboard enhancement must use the authenticated Supabase client rather than direct network requests.');

assert.match(css,/#dashboardPage \.dashboard-executive-grid/,'New layout must remain scoped to Dashboard.');
assert.match(css,/dashboard-personal-tools\{[\s\S]*?grid-template-columns:minmax\(0,3fr\) minmax\(300px,1fr\)/,'Quick Actions and Storage Usage must share one desktop row.');
assert.match(css,/dashboard-personal-actions\{[\s\S]*?grid-template-columns:repeat\(6,minmax\(106px,1fr\)\)/,'All six quick actions must stay in one row.');
assert.match(css,/dashboard-document-timeline-layout\{[\s\S]*?grid-template-columns:minmax\(0,3fr\) minmax\(300px,1fr\)/,'Document timeline must remain no wider than the Quick Actions column.');
assert.match(css,/dashboard-document-timeline-rows\{[\s\S]*?max-height:432px[\s\S]*?overflow-y:auto/,'Only eight 54px document rows may be visible before internal scrolling.');
assert.match(css,/dashboard-document-list-card\{grid-column:1;\}[\s\S]*?dashboard-document-bars-card\{grid-column:2;\}/,'Uploaded Documents and Time Remaining must occupy separate aligned desktop cards.');
assert.match(css,/dashboard-document-list-row,[\s\S]*?dashboard-document-bar-row\{[\s\S]*?height:54px[\s\S]*?min-height:54px/,'Document and expiry-bar rows must retain identical fixed heights.');
assert.match(css,/dashboard-document-list-rows,[\s\S]*?dashboard-document-bar-rows\{[\s\S]*?scrollbar-width:none/,'Both synchronized cards must remain scrollable without visible scrollbars.');
assert.match(css,/dashboard-document-sort\{[\s\S]*?background:transparent/,'Sort controls must remain compact and inherit the existing Dashboard design.');
assert.match(css,/@media\(max-width:560px\)/,'Mobile layout must be explicit.');
assert.match(css,/var\(--atsrs-ref-light-surface\)/,'Light mode must reuse ATSRS tokens.');
assert.match(css,/dashboard-storage-chart\{[\s\S]*?--dashboard-storage-accent:var\(--atsrs-brand-green/,'Dark storage chart must reuse the ATSRS green token.');
assert.match(css,/html\[data-theme="light"\][\s\S]*?--dashboard-storage-accent:var\(--atsrs-ref-blue/,'Light storage chart must reuse the ATSRS blue token.');
assert.match(css,/dashboard-personal-action:is\(:hover,:focus-visible\)[\s\S]*?border-top-color:var\(--atsrs-field-line\)[\s\S]*?border-bottom-color:var\(--atsrs-field-line\)[\s\S]*?border-left-color:var\(--atsrs-field-accent\)[\s\S]*?border-right-color:var\(--atsrs-field-accent\)/,'Quick Action hover and keyboard focus must reuse the shared ATSRS field edge geometry in both themes.');
assert.match(css,/dashboard-personal-action:is\(:hover,:focus-visible\)[\s\S]*?box-shadow:-3px 0 0 var\(--atsrs-field-accent-ring\),3px 0 0 var\(--atsrs-field-accent-ring\),0 8px 20px var\(--atsrs-field-accent-shadow\)/,'Quick Actions must use the same left/right edge glow as the Jobs Search field reference.');
assert.match(css,/data-theme="dark"[\s\S]*?dashboard-personal-action:not\(:hover\):not\(:focus-visible\)[\s\S]*?background:var\(--atsrs-field-surface,#0b0d0d\)!important/,'Unselected dark-mode Quick Actions must use the neutral black field surface instead of the legacy blue fill.');
assert.doesNotMatch(css,/dashboard-personal-action:hover\{[\s\S]*?(?:atsrs-brand-green[^}]*9%|atsrs-shell-accent-soft|0 8px 20px rgba\((?:34,197,94|22,123,211))/,'Legacy full-fill Quick Action hover colors and uniform shadow must be removed before applying the shared edge treatment.');
assert.match(css,/#dashboardManageStorage\{[\s\S]*?display:inline-flex!important[\s\S]*?text-decoration:none!important/,'Manage Storage must retain a compact button treatment while using native link navigation.');
assert.match(css,/var\(--atsrs-workspace-surface/,'Dark mode must reuse ATSRS workspace tokens.');
assert.doesNotMatch(css,/(^|\n)\s*(button|input|select|h1|\*)\s*\{/,'No unscoped global control or typography override is allowed.');
assert.match(harness,/mode=company|params\.get\('mode'\)/,'Harness must support Corporate visual QA.');
assert.match(harness,/theme.*light/,'Harness must support light-mode visual QA.');
assert.match(harness,/floating-field-standard-v58178\.css/,'Visual harness must load the shared ATSRS field tokens used by Quick Action edge lighting.');
assert.match(responsiveHarness,/iframe/,'Responsive QA must use a real nested viewport.');
assert.match(responsiveHarness,/Math\.max\(320/,'Responsive QA must cover mobile viewport widths.');

console.log('executive-dashboard-structure: PASS');
