const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const test=require('node:test');
const root=path.join(__dirname,'..');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const runtime=fs.readFileSync(path.join(root,'js','jobs-prototype.js'),'utf8');
const css=fs.readFileSync(path.join(root,'css','jobs-prototype.css'),'utf8');
const storage=fs.readFileSync(path.join(root,'js','storage.js'),'utf8');
const shellCss=fs.readFileSync(path.join(root,'css','shell-polish.css'),'utf8');
const shellRuntime=fs.readFileSync(path.join(root,'js','shell-polish.js'),'utf8');
const routeLoader=fs.readFileSync(path.join(root,'js','route-feature-loader.js'),'utf8');

test('Jobs is isolated, navigable and visibly live',()=>{
  assert.match(index,/id="navJobs"[^>]*showPage\('jobs'/);
  assert.match(index,/section id="jobsPage"[\s\S]*?LIVE JOBS/);
  assert.match(index,/jobs-prototype\.css\?v=58138/);
  assert.match(index,/route-feature-loader\.js\?v=58138/);
  assert.doesNotMatch(index,/<script src="js\/jobs-prototype\.js\?v=58138"><\/script>/);
  assert.match(routeLoader,/loadScript\('js\/jobs-prototype\.js\?v=58138'\)/);
  assert.match(routeLoader,/String\(page\|\|''\)==='jobs'/);
  assert.equal((storage.match(/jobs:navJobs/g)||[]).length,2);
  assert.match(shellCss,/#navJobs/);
  assert.ok(index.indexOf('id="navJobs"')<index.indexOf('id="navCandidates"'),'Jobs must appear above Candidates in both workspace sidebars');
  assert.match(shellRuntime,/navJobs:'briefcase-metal'/);
  assert.match(index,/shell-polish\.js\?v=567/);
  assert.match(index,/shell-polish\.css\?v=570/);
});

test('intentional Jobs sidebar navigation alone resets the shared page state',()=>{
  assert.match(index,/id="navJobs"[^>]*showPage\('jobs',this\);window\.dispatchEvent\(new CustomEvent\('atsrs:jobs-nav'\)\)/);
  assert.match(runtime,/function resetFromSidebar\(\)\{[\s\S]*?page=1;renderPagination\(\)/);
  assert.match(runtime,/section\.scrollIntoView\(\{block:'start',behavior:'auto'\}\)/);
  assert.match(runtime,/return load\(1\)/);
  assert.match(runtime,/addEventListener\('atsrs:jobs-nav',resetFromSidebar\)/);
  assert.match(runtime,/addEventListener\('atsrs:resume',function\(\)\{load\(page\)\}\)/);
  assert.match(runtime,/resetFromSidebar:resetFromSidebar/);
  assert.match(fs.readFileSync(path.join(root,'tests','fixtures','jobs-prototype-harness.html'),'utf8'),/id="navJobs"[^>]*atsrs:jobs-nav/);
  assert.match(fs.readFileSync(path.join(root,'tests','fixtures','jobs-prototype-harness.html'),'utf8'),/shell-polish\.css\?v=570-qa/);
  assert.match(fs.readFileSync(path.join(root,'tests','fixtures','jobs-prototype-harness.html'),'utf8'),/workspace-surface-standard-v519\.css\?v=519-qa/);
  const viewHandlerStart=runtime.indexOf("document.querySelectorAll('[data-jobs-view]'",runtime.indexOf('async function boot()'));
  const viewHandlerEnd=runtime.indexOf('isAdmin=await adminCheck()',viewHandlerStart);
  assert.ok(viewHandlerStart>=0&&viewHandlerEnd>viewHandlerStart);
  assert.doesNotMatch(runtime.slice(viewHandlerStart,viewHandlerEnd),/load\(/);
});

test('Jobs uses server data, safe DOM rendering and owner write controls',()=>{
  assert.match(runtime,/from\('atsrs_jobs'\)/);
  assert.match(runtime,/atsrs_jobs_admin_status/);
  assert.match(runtime,/\.insert\(p\)|\.update\(p\)/);
  assert.doesNotMatch(runtime,/service_role|innerHTML|outerHTML|insertAdjacentHTML|document\.write/);
  assert.match(runtime,/textContent=String\(text\)/);
  assert.match(runtime,/replaceChildren/);
  assert.match(runtime,/Recruiter email/);
  assert.match(runtime,/Recruiter organisation/);
  assert.doesNotMatch(runtime,/jobsManageButton|jobs-manage-button/);
  assert.doesNotMatch(runtime,/No candidate commission|job-fee-note/);
  assert.equal((index.match(/No candidate commission\./g)||[]).length,1);
  assert.match(index,/class="jobs-notice" role="note"[\s\S]*ph-warning[\s\S]*No candidate commission\./);
  assert.doesNotMatch(css,/job-fee-note/);
  assert.doesNotMatch(runtime,/ryan\.webster|ellie\.malim|cheryl\.nicolson/);
  assert.match(runtime,/Recruiter email/);
  assert.match(runtime,/Recruiter phone/);
  assert.doesNotMatch(runtime,/<details>|<summary>/);
  assert.match(runtime,/contact\(contacts,'Recruiter email',validEmail\(job\.recruiter_email\),'email',mailtoHref\(job\)\)/);
  assert.doesNotMatch(runtime,/Send email/);
  assert.doesNotMatch(runtime,/['"]tel:/);
  assert.doesNotMatch(index,/Recruiters use ATSRS through subscription plans/);
  assert.doesNotMatch(runtime,/Recruiters use ATSRS through subscription plans/);
});

test('Jobs uses exact-count server pagination and responsive zero-overflow layout',()=>{
  assert.match(runtime,/jobsSearch/);
  assert.match(runtime,/jobsRoleFilter/);
  assert.match(runtime,/jobsLocationFilter/);
  assert.match(index,/id="jobsPaginationTop"[^>]*aria-label="Jobs pagination"[^>]*data-jobs-pagination/);
  assert.match(index,/id="jobsPaginationBottom"[^>]*aria-label="Jobs pagination"[^>]*data-jobs-pagination/);
  assert.equal((index.match(/data-jobs-pagination/g)||[]).length,2);
  const jobsSection=index.slice(index.indexOf('<section id="jobsPage"'),index.indexOf('<section id="privacyPage"'));
  assert.doesNotMatch(jobsSection,/jobsLoadMore|Load more/);
  assert.doesNotMatch(runtime,/jobsLoadMore|cursor=null|more=false/);
  assert.match(runtime,/PAGE=30/);
  assert.match(runtime,/select\('\*',\{count:'exact'\}\)/);
  assert.match(runtime,/\.range\(from,from\+PAGE-1\)/);
  assert.match(runtime,/function applyFilters\(query,state,now\)/);
  assert.match(index,/id="jobsSearch"[^>]*placeholder="Job title or role"/);
  assert.match(index,/id="jobsSearch" type="search"/);
  assert.match(runtime,/\['jobsSearch','jobsCompanyFilter','jobsRecruiterFilter'\]/);
  assert.match(runtime,/query=query\.ilike\('title','%'\+term\+'%'\)/);
  assert.match(runtime,/load\(1\)/);
  assert.match(runtime,/jobs\.length\+' of '\+total/);
  assert.match(runtime,/aria-current','page/);
  assert.match(runtime,/aria-disabled','true/);
  assert.match(runtime,/jobs-page-chevron','‹'/);
  assert.match(runtime,/jobs-page-chevron','›'/);
  assert.match(runtime,/querySelectorAll\('\[data-jobs-pagination\]'\)/);
  assert.match(runtime,/renderPaginationNav\(nav,pages\)/);
  assert.match(runtime,/requestAnimationFrame\(focusResults\)/);
  assert.match(runtime,/top=id\('jobsPaginationTop'\)/);
  assert.match(css,/\.jobs-pagination\{[^}]*flex-wrap:nowrap[^}]*justify-content:flex-end[^}]*width:max-content[^}]*margin-left:auto/);
  assert.match(css,/\.jobs-pagination-top\{margin-top:-10px;margin-bottom:18px\}/);
  assert.match(css,/\.jobs-pagination-bottom\{margin-top:28px\}/);
  assert.match(css,/\.jobs-page-button\{[^}]*min-width:38px[^}]*height:38px[^}]*min-height:38px/);
  assert.match(css,/\.jobs-page-button\{[^}]*border:0[^}]*background:transparent[^}]*box-shadow:none/);
  assert.match(css,/jobs-page-button\.is-current[^\{]*\{background:var\(--atsrs-jobs-green-text\)!important;color:#071006!important\}/);
  assert.match(css,/html\[data-theme="light"\][^\{]*jobs-page-button\.is-current[^\{]*\{background:#245b93!important;color:#fff!important\}/);
  assert.match(css,/jobs-page-button:hover:not\(:disabled\):not\(\.is-current\)[^\{]*\{background:rgba\(148,163,184,\.1\)!important/);
  assert.match(css,/\.jobs-page-button:focus-visible\{outline:2px solid rgba\(158,234,115,\.62\);outline-offset:2px\}/);
  assert.match(css,/#jobsPage \.jobs-page-button\{min-width:38px!important;height:38px!important;min-height:38px!important;border:0!important;background:transparent!important;box-shadow:none!important\}/);
  assert.match(css,/@media\(max-width:600px\)[^{]*\{[\s\S]*?#jobsPage \.jobs-page-button\{min-width:36px!important;height:36px!important;min-height:36px!important\}/);
  assert.match(css,/jobs-page-edge[^\{]*\{min-width:92px!important\}/);
  assert.match(shellCss,/:not\(\.jobs-page-button\)/);
  assert.match(css,/\.jobs-page-edge-label\{display:none\}/);
  assert.match(css,/@media\(max-width:600px\)/);
  assert.match(css,/min-width:0/);
});

test('Jobs has exactly one non-duplicated accessible secondary filter system',()=>{
  const fixture=fs.readFileSync(path.join(root,'tests','fixtures','jobs-prototype-harness.html'),'utf8');
  assert.equal((index.match(/id="jobsSecondaryFilters"/g)||[]).length,1);
  assert.equal((fixture.match(/id="jobsSecondaryFilters"/g)||[]).length,1);
  ['jobsCompanyFilter','jobsRecruiterFilter','jobsDateFilter','jobsOffshoreFilter','jobsOnshoreFilter','jobsNewOnlyFilter','jobsActiveFilters','jobsMoreFilters'].forEach(id=>{
    assert.equal((index.match(new RegExp(`id="${id}"`,'g'))||[]).length,1,`${id} must exist exactly once`);
  });
  assert.match(index,/id="jobsCompanyFilter"[^>]*list="jobsCompanyOptions"/);
  assert.match(index,/id="jobsRecruiterFilter"[^>]*list="jobsRecruiterOptions"/);
  assert.match(index,/id="jobsNewOnlyFilter"[^>]*role="switch"/);
  assert.match(runtime,/querySelectorAll\('#jobsSecondaryFilters'\)\.length!==1/);
  assert.match(runtime,/function uniqueValues\(/);
  assert.match(runtime,/list\.replaceChildren\(frag\)/);
  assert.match(runtime,/function clearFilters\(\)/);
  assert.match(runtime,/setPressed\('jobsOffshoreFilter',false\)/);
  assert.match(runtime,/id\('jobsNewOnlyFilter'\)\.checked=false/);
  assert.match(css,/\.jobs-secondary-filters\{display:grid/);
  assert.match(css,/@media\(max-width:600px\)[^{]*\{[\s\S]*?\.jobs-more-filters\{display:inline-flex/);
});

test('Jobs supports persistent accessible card and list views',()=>{
  assert.match(index,/data-jobs-view="cards"/);
  assert.match(index,/data-jobs-view="list"/);
  assert.match(runtime,/atsrs_jobs_view/);
  assert.match(runtime,/aria-pressed/);
  assert.match(runtime,/jobs-list/);
  assert.match(css,/\.jobs-grid\.jobs-list/);
  assert.match(css,/\.jobs-list \.job-card-head\{display:grid;grid-template-columns:minmax\(0,1fr\) auto/);
  assert.match(css,/@media\(min-width:901px\)\{\.jobs-list \.job-contact-info\{padding-top:38px\}\}/);
  assert.match(shellCss,/#projectsPage,#jobsPage/);
  assert.doesNotMatch(css,/\.jobs-list \.job-contact-(?:org|source)\{display:none/);
  assert.doesNotMatch(css,/\.job-contact-phone\{display:none/);
  assert.match(runtime,/contact\(contacts,'Listing source'/);
  assert.match(runtime,/contact\(contacts,'Application'/);
  assert.doesNotMatch(runtime,/function action\(/);
  assert.match(runtime,/body=el\('div','job-card-body'\)/);
  assert.match(runtime,/body\.append\(project,c\);a\.append\(head,details,body\)/);
  assert.match(runtime,/function syncCardOverflow\(\)/);
  assert.match(runtime,/body\.scrollHeight>body\.clientHeight\+1/);
  assert.match(runtime,/body\.toggleAttribute\('data-overflow',scrollable\)/);
  assert.match(runtime,/body\.tabIndex=0/);
  assert.match(runtime,/requestAnimationFrame\(syncCardOverflow\)/);
  assert.match(css,/\.jobs-grid\.jobs-cards\{align-items:start\}/);
  assert.match(css,/\.jobs-cards \.job-card\{height:560px;max-height:560px;grid-template-rows:auto minmax\(0,1fr\);align-content:stretch\}/);
  assert.match(css,/\.jobs-cards \.job-card-body\{[^}]*min-height:0[^}]*overflow-x:hidden[^}]*overflow-y:auto[^}]*scrollbar-gutter:stable/);
  assert.match(css,/\.jobs-list \.job-card-body\{display:contents\}/);
  assert.match(css,/@media\(max-width:1250px\)\{[\s\S]*?\.jobs-cards \.job-card\{height:580px;max-height:580px\}/);
  assert.match(css,/@media\(max-width:900px\)\{[\s\S]*?\.jobs-cards \.job-card\{height:640px;max-height:640px\}/);
  assert.match(css,/@media\(max-width:600px\)[^{]*\{[\s\S]*?\.jobs-cards \.job-card\{height:min\(720px,calc\(100dvh - 24px\)\);max-height:min\(720px,calc\(100dvh - 24px\)\)\}/);
  assert.match(css,/html\[data-theme="light"\] \.jobs-cards \.job-card-body\{scrollbar-color:rgba\(83,102,128,\.34\) transparent\}/);
  assert.match(css,/\.jobs-cards \.job-card-body\[data-overflow\]:focus-visible\{outline:1px solid rgba\(158,234,115,\.34\)/);
});

test('Jobs renders only verified source and closing dates with card/list parity',()=>{
  assert.match(runtime,/job\.source_posted_at\|\|job&&job\.display_posted_date/);
  assert.match(runtime,/value\?'Posted '\+value:''/);
  assert.match(runtime,/fact\(dl,'Posted',dated\.replace\(\/\^Posted\\s\+\/,''\)\)/);
  assert.match(runtime,/fact\(dl,'Closing date',verifiedDate\(job\.closing_date\)\)/);
  assert.doesNotMatch(runtime,/prefix='Received '|Received /);
  assert.doesNotMatch(runtime,/dateLabel\([^)]*published_at/);
  assert.doesNotMatch(runtime,/job-status job-status-/);
  assert.match(runtime,/Intl\.DateTimeFormat\('en-GB'/);
});

test('Jobs detail overlay is shared, accessible and safely rendered',()=>{
  assert.match(runtime,/function detailContent\(job\)/);
  assert.match(runtime,/function openDetails\(job,opener\)/);
  assert.match(runtime,/dialog\.showModal\(\)/);
  assert.match(runtime,/expanded\?'Minimize job details':'Expand job details'/);
  assert.match(runtime,/ph-arrows-in':'ph-arrows-out/);
  assert.match(runtime,/ph ph-arrows-out/);
  assert.doesNotMatch(runtime,/ph ph-(?:minus|square)/);
  assert.doesNotMatch(runtime,/job-detail-(?:maximize|close)/);
  assert.doesNotMatch(runtime,/Restore vacancy details|Close vacancy details/);
  assert.match(runtime,/function dismissDetails\(dialog\)/);
  assert.match(runtime,/addEventListener\('cancel'/);
  assert.match(runtime,/e\.key!=='Tab'/);
  assert.match(runtime,/dialog\.addEventListener\('close'/);
  assert.match(runtime,/home\.parent\.insertBefore\(opener/);
  assert.match(runtime,/detailPageScrollY=window\.scrollY/);
  assert.match(runtime,/opener\.focus\(\{preventScroll:true\}\)/);
  assert.match(runtime,/window\.scrollTo\(0,detailPageScrollY\)/);
  assert.match(runtime,/document\.body\.classList\.add\('jobs-detail-open'\)/);
  assert.doesNotMatch(runtime,/innerHTML|insertAdjacentHTML|document\.write/);
  assert.match(css,/body #jobsPage \.job-detail-toggle,body \.job-detail-dialog \.job-detail-toggle\{[^}]*top:8px[^}]*right:8px[^}]*width:28px[^}]*height:28px[^}]*border-radius:50%!important/);
  assert.match(css,/#app\.app:not\(\.hidden\)>\.main #jobsPage \.job-detail-toggle[^}]*width:28px!important[^}]*height:28px!important[^}]*min-width:28px!important[^}]*min-height:28px!important/);
  assert.match(css,/\.job-detail-controls\{display:contents\}/);
  assert.doesNotMatch(css,/job-detail-dialog\.is-maximized|job-detail-maximize|job-detail-close/);
  assert.match(css,/background:#111214!important[^}]*color:#f8fafc!important/);
  assert.match(css,/\.job-detail-toggle::after[^}]*inset:-8px[^}]*border-radius:50%/);
  assert.doesNotMatch(css,/\.ph-square::before|\.ph-minus::before/);
  assert.match(css,/html\[data-theme="light"\] body #jobsPage \.job-detail-toggle,html\[data-theme="light"\] body \.job-detail-dialog \.job-detail-toggle\{[^}]*border-color:#d8e1ee!important[^}]*background:#fff!important[^}]*color:#245b93!important/);
  assert.match(css,/repeat\(auto-fit,minmax\(190px,1fr\)\)/);
  assert.match(css,/@media\(prefers-reduced-motion:reduce\)[^{]*\{[^}]*\.job-new-badge i\{animation:none\}\.job-detail-dialog,\.job-detail-toggle\{transition:none\}/);
  assert.match(css,/@media\(max-width:600px\)[^{]*\{[\s\S]*?\.job-detail-dialog\{width:100vw;height:100dvh/);
  assert.match(css,/\.job-detail-dialog\[open\]:not\(\.is-leaving\)\{transform:scale\(1\)\}/);
  assert.match(css,/html\[data-theme="light"\] body #app\.app:not\(\.hidden\) #jobsPage \.jobs-view-switch\{border-color:transparent!important/);
});

test('Jobs card and dialog controls share one uniform title-aligned interaction contract',()=>{
  assert.match(css,/\.job-card-head h2\{[^}]*padding-right:42px/);
  assert.match(css,/body #jobsPage \.job-detail-toggle:hover,body \.job-detail-dialog \.job-detail-toggle:hover\{[^}]*background:#1a1c1e!important/);
  assert.match(css,/body #jobsPage \.job-detail-toggle:active,body \.job-detail-dialog \.job-detail-toggle:active\{[^}]*transform:scale\(\.95\)/);
  assert.match(css,/body #jobsPage \.job-detail-toggle:focus-visible,body \.job-detail-dialog \.job-detail-toggle:focus-visible\{[^}]*outline:2px solid rgba\(248,250,252,\.82\)!important[^}]*outline-offset:2px!important/);
  assert.match(css,/html\[data-theme="light"\][^{]*\.job-detail-toggle:active[^}]*background:#e2ecf7!important[^}]*color:#245b93!important[^}]*transform:scale\(\.95\)/);
  assert.match(css,/html\[data-theme="light"\][^{]*\.job-detail-toggle:focus-visible[^}]*outline:2px solid #1d4ed8!important[^}]*outline-offset:2px!important/);
  assert.equal((runtime.match(/el\('button','job-detail-toggle'\)/g)||[]).length,1);
  assert.equal((shellCss.match(/:not\(\.job-detail-toggle\)/g)||[]).length,3);
  assert.doesNotMatch(runtime,/el\('button','job-detail-control job-detail-minimize'\)/);
  assert.match(runtime,/replaceChildren\(opener\)/);
  assert.match(runtime,/e\.key!=='Enter'&&e\.key!==' '/);
  assert.match(runtime,/details\.addEventListener\('keydown',detailControlKeydown\)/);
  assert.doesNotMatch(runtime,/e\.target===dialog/);
  assert.match(runtime,/addEventListener\('cancel',function\(e\)\{e\.preventDefault\(\)\}\)/);
});

test('Jobs view controls and inline notice use the approved palettes',()=>{
  assert.match(css,/\.jobs-notice\{[^}]*width:max-content[^}]*padding:0[^}]*border:0[^}]*background:transparent[^}]*color:#bd6b72/);
  assert.match(css,/html\[data-theme="light"\] \.jobs-notice\{color:#9f3f49\}/);
  assert.match(css,/html\[data-theme="light"\] \.jobs-notice p\{color:#9f3f49!important\}/);
  assert.match(css,/#jobsPage \.jobs-view-switch\{[^}]*border-color:transparent!important[^}]*background:#050706!important/);
  assert.match(css,/#jobsPage \.jobs-view-switch button\{[^}]*min-height:44px!important[^}]*border:0!important/);
  assert.match(css,/#jobsPage \.jobs-view-switch button\[aria-pressed="true"\]::after/);
  assert.match(css,/html\[data-theme="light"\][^{]*#jobsPage \.jobs-view-switch button,html\[data-theme="light"\][^{]*#jobsPage \.jobs-view-switch button:hover\{[^}]*background:transparent!important/);
  assert.match(css,/html\[data-theme="light"\][^{]*#jobsPage \.jobs-view-switch button\[aria-pressed="true"\][^}]*\{background:transparent!important[^}]*color:#245b93!important/);
});
