const assert=require('node:assert/strict');
const fs=require('node:fs');
const shell=fs.readFileSync('js/shell-polish.js','utf8');
const css=fs.readFileSync('css/shell-polish.css','utf8');
const html=fs.readFileSync('index.html','utf8');

assert.match(shell,/atsrsNotificationPopover/);
assert.match(shell,/atsrsGetOwnerShareRequests/);
assert.match(shell,/item\.status==='pending'/);
assert.match(shell,/showAccountTab\('sharing'\)/);
assert.match(shell,/profile-sharing-link-request\[data-request-id=/);
assert.match(css,/\.atsrs-notification-popover\{/);
assert.match(css,/\.atsrs-notification-badge\{/);
assert.match(html,/css\/shell-polish\.css\?v=5880/);
assert.match(html,/js\/shell-polish\.js\?v=578/);
assert.match(shell,/params\.set\('tab','sharing'\)/);
assert.match(shell,/byId\('navProfile'\)/);
assert.match(shell,/\[0,120,320,700,1400,2400\]/);
assert.match(css,/\.atsrs-shell-notification-list\{[^}]*max-height:500px[^}]*overflow:auto/);
assert.match(css,/\.atsrs-shell-notification-item\{[^}]*grid-template-columns:58px minmax\(0,1fr\) 76px!important/);
assert.match(css,/width:min\(620px,calc\(100vw - 32px\)\)/);
assert.match(css,/\.atsrs-notification-popover::before/);
assert.match(shell,/syncNotificationPopoverCaret/);
assert.match(shell,/atsrs-shell-notification-icon/);
assert.match(shell,/event\.key==='Escape'/);
assert.match(shell,/atsrs-notification-popover-close/);
assert.match(shell,/atsrs-notification-popover-view-all/);
assert.match(shell,/>Clear all</);
assert.match(shell,/clearNotificationPopover/);
assert.match(shell,/atsrs_dismissed_request_notifications/);
assert.match(css,/#atsrsNotificationButton\{position:relative!important\}/);
assert.match(css,/#atsrsNotificationButton \.atsrs-notification-badge\{color:#fff!important/);
assert.match(css,/\.atsrs-notification-badge\[hidden\]\{display:none!important\}/);
console.log('Notification popover request routing contracts passed');
