const assert=require('node:assert/strict');
const fs=require('node:fs');
const shell=fs.readFileSync('js/shell-polish.js','utf8');
const css=fs.readFileSync('css/shell-polish.css','utf8');
const html=fs.readFileSync('index.html','utf8');

assert.match(shell,/atsrsNotificationPopover/);
assert.match(shell,/atsrsGetOwnerShareRequests/);
assert.match(shell,/item\.status==='pending'/);
assert.match(shell,/showAccountTab\('sharing'\)/);
assert.match(shell,/profile-sharing-link-request\[data-request-id=/);
assert.match(css,/\.atsrs-notification-popover\{/);
assert.match(css,/\.atsrs-notification-badge\{/);
assert.match(html,/css\/shell-polish\.css\?v=5874/);
assert.match(html,/js\/shell-polish\.js\?v=575/);
assert.match(css,/\.atsrs-shell-notification-list\{[^}]*max-height:326px[^}]*overflow:auto/);
assert.match(css,/\.atsrs-shell-notification-item\{[^}]*grid-template-columns:34px minmax\(0,1fr\) auto!important/);
assert.match(shell,/atsrs-shell-notification-icon/);
assert.match(shell,/event\.key==='Escape'/);
assert.match(shell,/atsrs-notification-popover-close/);
assert.match(shell,/clearNotificationPopover/);
assert.match(shell,/atsrs_dismissed_request_notifications/);
assert.match(css,/#atsrsNotificationButton\{position:relative!important\}/);
assert.match(css,/#atsrsNotificationButton \.atsrs-notification-badge\{color:#fff!important/);
assert.match(css,/\.atsrs-notification-badge\[hidden\]\{display:none!important\}/);
console.log('Notification popover request routing contracts passed');
