const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'css','product-updates-atlas-v6010.css'),'utf8');
const js=fs.readFileSync(path.join(root,'js','product-updates-atlas-v6004.js'),'utf8');
const updates=index.slice(index.indexOf('<section id="introPage"'),index.indexOf('<section id="jobsPage"'));

test('Product Updates exposes the scalable release atlas',()=>{
  assert.match(index,/product-updates-atlas-v6010\.css\?v=6027/);
  assert.match(index,/product-updates-atlas-v6004\.js\?v=6027/);
  assert.match(updates,/class="updates-atlas"/);
  assert.equal((updates.match(/class="atlas-marker/g)||[]).length,8);
  assert.equal((updates.match(/class="atlas-marker is-live/g)||[]).length,5);
  assert.equal((updates.match(/class="atlas-marker is-building/g)||[]).length,1);
  assert.equal((updates.match(/class="atlas-marker is-next/g)||[]).length,2);
  assert.doesNotMatch(updates,/data-atlas-view=/);
  assert.doesNotMatch(updates,/>Atlas<|>List</);
  assert.match(css,/grid-template-columns:minmax\(0,1fr\) 308px/);
  assert.match(css,/width:min\(100%,1440px\)!important/);
  assert.match(css,/width:max-content!important;max-width:230px!important/);
  assert.match(css,/html\[data-theme="light"\] \.atlas-stats-grid>div/);
  assert.match(css,/release-atlas-texture-light-v6010\.png/);
  assert.match(css,/html\[data-theme="dark"\] \.atlas-map-texture\{opacity:\.96;filter:brightness\(1\.7\) contrast\(\.92\) saturate\(1\.08\)\}/);
  assert.match(css,/html\[data-theme="light"\] \.atlas-map-texture\{[^}]*filter:brightness\(\.94\) contrast\(1\.28\) saturate\(1\.08\);opacity:\.98/);
  assert.match(updates,/class="atlas-route-lines"/);
  assert.match(updates,/class="updates-atlas-detail atlas-pricing-showcase"/);
  assert.match(js,/setLineDash\(\[4,7\]\)/);
  assert.match(js,/routeAlpha=isLight\?\.58:\.92/);
  assert.match(js,/ResizeObserver\)new ResizeObserver\(scheduleRoutes\)\.observe\(canvas\)/);
  assert.match(js,/warmupCount>=16/);
  assert.match(js,/setInterval\(function\(\)\{showPlan\(planIndex\+1\)\},10000\)/);
  assert.match(js,/name:'BRONZE'/);
  assert.match(js,/name:'TITAN'/);
  assert.match(js,/title:'Active Job Seekers'/);
  assert.match(js,/title:'Frequent Career Activity'/);
  assert.match(js,/title:'Intensive Career Management'/);
  assert.match(js,/title:'Maximum Personal Capacity'/);
  assert.match(css,/\.is-building :is\(span,strong\)\{color:var\(--atlas-yellow\)!important\}/);
  assert.match(css,/white-space:nowrap!important/);
  assert.match(updates,/>All plans <i class="ph ph-arrow-up-right"/);
  assert.match(css,/release-atlas-texture-v6004\.png/);
  assert.match(css,/@media\(max-width:760px\)/);
  const showcase=updates.slice(updates.indexOf('atlas-pricing-showcase'),updates.indexOf('</aside>',updates.indexOf('atlas-pricing-showcase')));
  assert.doesNotMatch(showcase,/Product status/);
  assert.doesNotMatch(showcase,/Live<\/span><strong>5/);
  assert.match(showcase,/PERSONAL PLANS/);
  assert.match(css,/\.atlas-plan-card\.is-gold/);
  assert.match(css,/\.atlas-plan-navigation\{[^}]*padding:4px;[^}]*border:1px solid[^}]*border-radius:999px/);
  assert.match(css,/\.atlas-plan-arrow i\{[^}]*font-size:19px!important;[^}]*-webkit-text-stroke:\.45px currentColor/);
  assert.match(css,/\.atlas-plan-navigation \.atlas-plan-link\{[^}]*border-inline:1px solid/);
  assert.match(css,/@keyframes atlasPlanShine/);
  assert.match(css,/\.atlas-plan-card::after/);
  assert.match(css,/@keyframes atlasPlanRollIn/);
  assert.match(css,/@keyframes atlasPlanRollOut/);
  assert.match(css,/atlasPlanRollIn \.9s/);
  assert.match(js,/\},920\)/);
  assert.match(js,/planCardMarkup\(plan,true\)/);
  assert.match(js,/showPlan\(0,true\)/);
  assert.match(css,/animation:atlasPlanShine 2\.8s[^}]* 4s 1 both/);
  assert.match(css,/\.atlas-marker span\{color:#245f9f!important/);
});

test('Atlas interactions are data-driven and retain working launch actions',()=>{
  assert.match(js,/var releases=\{/);
  assert.match(js,/atsrsOpenJobsDirectory\('recruiters'/);
  assert.match(js,/atsrsOpenJobsDirectory\('employers'/);
  assert.match(js,/dataAtlasMode|dataset\.atlasMode/);
  assert.match(js,/querySelectorAll\('\.atlas-marker'\)/);
  assert.match(js,/context\.lineTo\(elbowX,elbowY\)/);
  assert.match(js,/openReleaseCard\(item,selectedMarker\)/);
  assert.match(js,/Math\.min\(canvasBox\.height-280,markerBox\.top-canvasBox\.top-72\)/);
  assert.match(js,/Math\.max\(cardTop\+40,Math\.min\(cardBottom-40,markerY-58\)\)/);
});
