const assert=require('node:assert/strict');
const fs=require('node:fs');
const html=fs.readFileSync('index.html','utf8');
const js=fs.readFileSync('js/profile-privacy-v1.js','utf8');
const css=fs.readFileSync('css/profile-privacy-v1.css','utf8');

['public','custom','private'].forEach(mode=>assert.match(html,new RegExp(`name="profilePrivacyMode" value="${mode}"`)));
['phone','email','location','availability','position','birthDate'].forEach(field=>assert.match(js,new RegExp(`key:'${field}'`)));
assert.doesNotMatch(js,/title:'Expected salary'/);
assert.doesNotMatch(js,/title:'About me'/);
assert.doesNotMatch(html,/id="profilePrivacyAudience"/);
assert.doesNotMatch(html,/id="profilePrivacyVisibilityTitle"/);
assert.doesNotMatch(html,/class="profile-privacy-heading"/);
assert.doesNotMatch(html,/id="profilePrivacyInformationTitle"/);
assert.doesNotMatch(html,/Information Visibility/);
assert.match(html,/id="profilePrivacyRows"/);
assert.doesNotMatch(html,/id="profilePrivacyResetBtn"/);
assert.doesNotMatch(html,/id="profilePrivacySaveBtn"/);
assert.match(js,/privacySettings=clone\(draft\)/);
assert.match(js,/function scheduleSave\(\)/);
assert.match(js,/window\.atsrsCloudData\.flush/);
assert.match(js,/mode==='public'\?'Public':mode==='private'\?'Private':'Link Only'/);
assert.match(css,/:has\(#profileTabPrivacyPanel\.is-active\)/);
assert.match(css,/@media\(max-width:620px\)/);
assert.match(css,/profile-privacy-mode-card\{[^}]*min-height:34px;[^}]*padding:4px 22px 4px 8px/);
assert.match(css,/:has\(#profileTabPrivacyPanel\.is-active\)\{height:294px;min-height:294px;max-height:294px\}/);
assert.match(css,/profile-privacy-matrix-row\{min-height:36px;/);
assert.match(css,/profile-privacy-mode-grid\{[^}]*grid-template-columns:repeat\(3,max-content\);[^}]*justify-content:start;[^}]*gap:8px/);
assert.match(css,/profile-privacy-mode-card small\{display:none\}/);
assert.match(html,/profile-privacy-matrix-head[^>]*><div class="profile-privacy-mode-grid"/);
assert.match(html,/css\/profile-privacy-v1\.css\?v=12/);
assert.match(html,/js\/profile-privacy-v1\.js\?v=4/);
console.log('Profile Privacy V1 contracts passed');
