const assert=require('node:assert/strict');
const fs=require('node:fs');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('css/profile-sharing-v1.css','utf8');
const js=fs.readFileSync('js/profile-sharing-v1.js','utf8');
const shareJs=fs.readFileSync('js/share-profile.js','utf8');
const recruiterJs=fs.readFileSync('js/recruiters.js','utf8');

assert.match(html,/id="profileSharingV1"/);
assert.match(html,/name="profileSharingAudience" value="recipient" checked/);
assert.equal((html.match(/name="profileSharingAudience"/g)||[]).length,1,'Only Specific recipient may be offered.');
assert.match(html,/name="profileSharingExpiry"/);
assert.match(html,/id="profileSharingActiveList"/);
assert.match(html,/id="profileSharingCreateBtn"/);
assert.match(html,/id="profileSharingDocumentDialog"/);
assert.doesNotMatch(html,/id="profileSharingV1"[\s\S]*?<h[1-6][^>]*>Sharing<\/h[1-6]>/);
assert.doesNotMatch(html,/id="profileSharingV1"[\s\S]*?Create share links to let others/);
assert.doesNotMatch(html,/id="profileSharingV1"[\s\S]*?Create Share Link/);
assert.match(css,/profile-sharing-v1\{[^}]*height:100%/);
assert.match(css,/grid-template-rows:76px minmax\(0,1fr\)/);
assert.match(css,/profile-sharing-setup\{[^}]*padding:0;[^}]*border:0;[^}]*background:transparent/);
assert.doesNotMatch(css,/:is\(\.profile-sharing-setup,\.profile-sharing-audience-grid/);
assert.match(css,/@media\(max-width:760px\)/);
assert.doesNotMatch(js,/window\.copyShareLink/);
assert.doesNotMatch(js,/window\.previewShareProfile/);
assert.match(js,/window\.deleteShareProfileLink/);
assert.match(html,/css\/profile-sharing-v1\.css\?v=45/);
assert.match(css,/:is\(\.profile-sharing-row-actions,\.profile-sharing-link-request-actions\)>button\{[^}]*height:22px!important;[^}]*min-height:22px!important;[^}]*max-height:22px!important/);
assert.match(css,/profile-sharing-expiry-check/);
assert.match(css,/profile-sharing-v1 \*\{box-sizing:border-box\}/);
assert.match(css,/profile-sharing-expiry-options label\.is-selected \.profile-sharing-expiry-check/);
assert.match(css,/profile-sharing-audience-grid label\.is-selected/);
assert.doesNotMatch(css,/profile-sharing-audience-grid label:has\(input:checked\)/);
assert.match(css,/profile-sharing-expiry-check\{[^}]*box-shadow/);
assert.match(css,/grid-template-columns:minmax\(0,180px\)/);
assert.doesNotMatch(html,/Information included/);
assert.doesNotMatch(html,/View details/);
assert.match(js,/syncCustomDate\(\)/);
assert.match(html,/js\/profile-sharing-v1\.js\?v=37/);
assert.match(html,/js\/share-profile\.js\?v=438/);
assert.match(js,/window\.showProfileWorkspaceTab\('sharing',false\)/);
assert.match(js,/function syncCreateAvailability\(\)/);
assert.match(js,/value==='custom'&&!\(custom&&custom\.value\)/);
assert.match(js,/wrap\.dataset\.collapsed='true';renderExpiry\(\)/);
assert.match(js,/function bindCustomExpiryOpen\(\)/);
assert.match(js,/setTimeout\(function\(\)\{if\(custom\)custom\.click\(\)\},0\)/);
assert.match(css,/profile-sharing-custom-expiry\.is-collapsed\{display:none!important\}/);
assert.match(html,/id="profileSharingDocumentSelectAll"/);
assert.match(js,/input\.checked=false/);
assert.match(js,/function bindDocumentSelectAll\(\)/);
assert.match(js,/function remainingTime\(value\)/);
assert.match(js,/recipient:'Specific recipient'/);
assert.match(shareJs,/token\.slice\(-8\)!==activeShare\.token_hint/);
assert.match(shareJs,/atsrsGetActiveShareStatus/);
assert.match(shareJs,/function validateShareToken\(token\)/);
assert.match(shareJs,/function createValidatedShare\(fileIds,expiresAt,audience\)/);
assert.match(shareJs,/window\.atsrsGetShares/);
assert.match(shareJs,/atsrsGetShares=function\(\)[\s\S]*?right\.updated_at\|\|right\.created_at[\s\S]*?return rightTime-leftTime/,'Share history must render newest or most recently updated first.');
assert.match(shareJs,/atsrsGetActiveShares=function\(\)[\s\S]*?filter\(function\(share\)\{return share\.active;\}\)/);
assert.match(shareJs,/audience:audience/);
assert.match(shareJs,/share_id:shareId/);
assert.match(js,/window\.deleteShareProfileLink\(share\.id\)/);
assert.match(shareJs,/await validateShareToken\(token\)/);
assert.match(shareJs,/window\.previewShareProfile=function\(shareId\)[\s\S]*?window\.open\(url,'_blank'\)/);
assert.match(shareJs,/safeOwnerGet\(OWNER_TOKEN_KEY\+'_map'\)/);
assert.match(shareJs,/This older link cannot be opened because its secure key is no longer stored in this browser/);
assert.match(shareJs,/window\.alert\(missingOpen\)/);
assert.doesNotMatch(css,/translateY\(-1px\)/);
assert.doesNotMatch(shareJs,/window\.previewShareProfile[^;]*setKnownLink\(''\)/);
assert.match(js,/Loading uploaded documents/);
assert.match(js,/function showDocumentDialog\(dialog\)/);
assert.match(js,/dialog\.setAttribute\('open',''\)/);
assert.match(js,/document\.body\.appendChild\(dialog\)/);
assert.match(js,/dialog\.style\.display='block'/);
assert.match(js,/theme\.getPropertyValue\('--surface'\)/);
assert.match(js,/dialog\.style\.background=/);
assert.match(html,/id="profileSharingSaveBtn"/);
assert.match(html,/id="profileSharingCancelBtn"/);
assert.match(html,/id="profileSharingEditBtn"/);
assert.match(js,/SHARING_SETUP_STORAGE_KEY='atsrs_profile_sharing_setup'/);
assert.match(js,/SHARING_SETUP_METADATA_KEY='atsrs_profile_sharing_setup'/);
assert.match(js,/auth\.updateUser\(\{data:\{atsrs_profile_sharing_setup:value\}\}\)/);
assert.match(js,/auth\.getUser\(\)/);
assert.match(js,/window\.addEventListener\('focus'/);
assert.match(js,/atsrs:cloud-data-loaded'[\s\S]*?refreshServerSetup\(true\)/);
assert.match(js,/function setEditing\(value\)/);
assert.match(js,/applySetup\(savedSetup\);setEditing\(false\)/);
assert.match(js,/dataset\.wasChecked==='true'/);
assert.match(js,/label\.addEventListener\('pointerdown'/);
assert.match(js,/atsrsPrepareProfileShare/);
assert.doesNotMatch(js,/dialog\.showModal\(\)/);
assert.match(js,/create\.disabled=!editing\|\|!value/);
assert.match(js,/if\(!editing\|\|button&&button\.disabled\)return/);
assert.match(js,/Save the sharing settings to finish/);
assert.doesNotMatch(js,/create\.disabled=[^\n]*audienceValue\(\)==='recipient'/,'Specific recipient must allow Create Link after an expiry is selected.');
assert.match(js,/window\.atsrsUpdateCurrentShareExpiry/,'Saving sharing settings must update the active server link expiry.');
assert.match(shareJs,/window\.atsrsUpdateCurrentShareExpiry=async function/);
assert.match(shareJs,/action:'update_expiry',share_id:activeShare\.id,expires_at:expiresAt/);
assert.match(shareJs,/activeShares=activeShares\.filter\(function\(share\)\{return share\.id!==deletedId;\}\)/,'A deleted link must disappear from local sharing history immediately.');
assert.doesNotMatch(shareJs,/if\(audience==='recipient'\)/,'Specific recipient creation must not be blocked in the profile Sharing flow.');
assert.match(shareJs,/refreshOwnerPanel\(\{force:true\}\);setTimeout\(function\(\)\{refreshOwnerPanel\(\{force:true\}\);\},1200\)/);
assert.match(css,/profile-sharing-document-dialog::backdrop/);
assert.match(css,/profile-sharing-create-button/);
assert.match(css,/profile-sharing-expiry-main>\.profile-sharing-create-button\{[^}]*height:48px!important;[^}]*min-height:48px!important/);
assert.match(css,/profile-sharing-expiry-main>\.profile-sharing-create-button\{[^}]*width:116px!important;[^}]*justify-content:flex-start!important/);
assert.match(css,/profile-sharing-expiry-main>\.profile-sharing-create-button>i\{[^}]*width:28px;[^}]*height:28px/);
assert.match(css,/linear-gradient\(135deg,#16a34a,#22c55e\)/);
assert.match(css,/profile-sharing-v1:not\(\.is-editing\) \.profile-sharing-setup\{pointer-events:none\}/);
assert.match(css,/profile-sharing-v1:not\(\.is-editing\) \.profile-sharing-expiry-main>\.profile-sharing-create-button\{pointer-events:auto\}/);
assert.match(html,/profile-sharing-links-heading-floating/);
assert.match(html,/profile-sharing-expiry-main/);
assert.match(css,/profile-sharing-history-only\{[^}]*grid-template-rows:34px minmax\(0,1fr\)/);
assert.match(css,/profile-sharing-active-list\{display:block;min-height:0;overflow:auto;border-top:1px solid var\(--line\)\}/);
assert.match(js,/atsrsGetOwnerShareRequests/);
assert.match(js,/profile-sharing-link-request/);
assert.match(js,/profile-sharing-row-requester/);
assert.doesNotMatch(js,/profile-sharing-row-decisions/);
assert.match(js,/profile-sharing-row-requester[^']*profile-sharing-row-status[^']*profile-sharing-row-time[^']*profile-sharing-row-actions/);
assert.match(js,/requester_company\|\|'Company not provided'/);
assert.match(js,/requester_email\|\|'Email not provided'/);
assert.match(js,/requestedCount\?requestedCount\+' file'/);
assert.match(js,/All shared files requested/);
assert.match(js,/shareRequests=requests\.filter\(function\(request\)\{return request\.share_id===share\.id\}\)/);
assert.doesNotMatch(js,/request\.share_id===share\.id&&request\.status==='pending'/);
assert.match(js,/value==='approved'\?'Approved'/);
assert.match(css,/profile-sharing-request-state\.status-approved/);
assert.match(css,/html\[data-theme="dark"\][^{]*profile-sharing-link-request[\s\S]*?background:var\(--surface,#0b0f0d\)!important/);
assert.match(js,/decideShareRequest\(request\.id,'approve'/);
assert.match(js,/setTimeout\(applyEmailRoute,350\)/);
assert.doesNotMatch(js,/approve\.focus\(\)/);
assert.match(css,/profile-sharing-link-request\{/);
assert.match(css,/grid-template-columns:minmax\(170px,\.95fr\) minmax\(270px,1\.45fr\) 72px minmax\(118px,\.62fr\) auto/);
assert.match(css,/html\[data-theme="light"\][^{]*\.profile-sharing-row-status\{color:#2563eb\}/);
assert.match(css,/profile-sharing-link-request-actions button\{[^}]*min-width:0!important;[^}]*height:22px!important;[^}]*max-height:22px!important;[^}]*padding:0 6px!important/);
assert.match(css,/profile-sharing-request-state\{[^}]*min-width:0;[^}]*height:22px;[^}]*max-height:22px;[^}]*padding:0 6px/);
assert.match(css,/html\[data-theme="dark"\][^{]*profile-sharing-row\.is-email-focus[\s\S]*?background:var\(--surface,#0b0f0d\)!important/);
assert.match(css,/profile-sharing-link-request-actions>button:not\(\.is-danger\)\{[^}]*border-color:color-mix\([^}]*color:var\(--atsrs-field-accent,#22c55e\)!important/);
assert.match(css,/profile-sharing-link-request-actions>button\.is-danger\{[^}]*border-color:color-mix\(in srgb,#ef4444 58%,var\(--line\)\)!important;[^}]*color:#ef4444!important/);
assert.match(css,/html\[data-theme="dark"\] \.profile-sharing-document-dialog\{background:#080b0a!important\}/);
assert.match(js,/function isServerRecord\(value\)/);
assert.match(js,/\.filter\(isServerRecord\)/);
assert.doesNotMatch(js,/['"] · Link ['"]\+recipientNumber/);
assert.match(js,/action\('Approve'[\s\S]*?action\('Decline'[\s\S]*?action\('View recruiter'[\s\S]*?action\('Edit'[\s\S]*?action\('Delete'/,'Sharing row actions must remain ordered: request decisions, recruiter navigation, Edit, and Delete.');
assert.match(shareJs,/window\.editShareProfileLink=async function/,'Edit must update a real server link expiry.');
assert.match(shareJs,/window\.deleteShareProfileLink=window\.revokeShareProfileLink/,'Delete must use the server-backed full link deletion flow.');
assert.match(html,/js\/recruiters\.js\?v=6047/);
assert.match(recruiterJs,/window\.focusRecruiterCard = async function/,'History must expose recruiter-card navigation.');
assert.match(recruiterJs,/attempt < 24 && !targetRecruiter/,'Recruiter navigation must wait for the asynchronous directory load.');
assert.match(recruiterJs,/card\.scrollIntoView\(\{ behavior: "smooth", block: "center" \}\)/);
assert.match(js,/if\(request\.status==='pending'\)/,'Approve and Decline must only render for a real pending download request.');
assert.match(js,/No download request/);
const edgeFunction=fs.readFileSync('supabase/functions/share-profile/index.ts','utf8');
assert.match(edgeFunction,/if \(action === "revoke"\)[\s\S]*?\.delete\(\)\.eq\("id", target\.id\)/,'Revoke must delete the owned share record on the server.');
assert.match(edgeFunction,/if \(action === "update_expiry"\)[\s\S]*?\.update\(\{ expires_at: expiresAt/,'Expiry edits must update the active server share.');
assert.doesNotMatch(edgeFunction,/if \(audience === "recipient"\)[\s\S]*?Choose a verified recruiter from Recruiter Directory/,'The server must accept profile Sharing links for the selected recipient audience.');
assert.match(edgeFunction,/const audience = "recipient" as ShareRow\["audience"\]/,'New profile links must always use the specific-recipient audience.');
console.log('Profile Sharing V1 contracts passed');
