const assert=require('node:assert/strict');
const fs=require('node:fs');
const html=fs.readFileSync('index.html','utf8');
const js=fs.readFileSync('js/profile-workspace-v5886.js','utf8');
const dashboard=fs.readFileSync('js/dashboard.js','utf8');
const datePicker=fs.readFileSync('js/date-picker.js','utf8');
const css=fs.readFileSync('css/profile-production-parity-v5878.css','utf8');

['Personal','Privacy','Sharing','Security'].forEach(name=>{
  assert.match(html,new RegExp(`id="profileTab${name}Btn"[^>]+aria-controls="profileTab${name}Panel"`));
  assert.match(html,new RegExp(`id="profileTab${name}Panel"[^>]+role="tabpanel"[^>]+aria-labelledby="profileTab${name}Btn"`));
});
assert.doesNotMatch(html,/profileTab(?:Privacy|Sharing|Security)Btn[^>]+aria-disabled/);
assert.match(js,/event\.key==='ArrowRight'\|\|event\.key==='ArrowLeft'/);
assert.match(js,/PROFILE_TAB_STORAGE_KEY='atsrs_profile_active_tab'/);
assert.match(js,/activate\(savedTab\(\),false\)/);
assert.match(js,/rememberTab\(name\)/);
assert.match(js,/Discard unsaved profile changes/);
assert.match(js,/cloneSelect\(country,'profileInlineNationality','Nationality'\)/);
assert.match(js,/select\.appendChild\(option\.cloneNode\(true\)\)/);
assert.doesNotMatch(js,/nationality\.addEventListener\('change'/);
assert.match(dashboard,/nationality:val\('profileInlineNationality'\)\|\|existing\.nationality\|\|val\('profileCountry'\)/);
assert.match(dashboard,/setVal\('profileInlineNationality',p\.nationality\|\|p\.country\)/);
assert.match(dashboard,/\['profileStageNationality',p\.nationality\|\|p\.country\]/);
assert.match(js,/select\.setAttribute\('data-atsrs-no-field-shell','true'\)/);
assert.match(js,/customSelect\(3,[\s\S]*?'profileInlineNationalityValue'/);
assert.match(js,/select\.addEventListener\('input'/);
assert.doesNotMatch(js,/profile-nationality-caret/);
assert.match(js,/profileInlineCountryResidence/);
assert.match(js,/profileInlineCompany/);
assert.match(js,/profileInlineBirthCountry/);
assert.match(js,/profileInlineCity/);
assert.match(js,/profileInlineTimezone/);
assert.match(js,/PROFILE_CITIES/);
assert.match(js,/populateCitySelect\(city,birthCountry\.value,''\)/);
assert.doesNotMatch(js,/profile-country-menu/);
assert.match(js,/box\.querySelectorAll\('i'\)\.forEach/);
assert.doesNotMatch(css,/\.profile-nationality-select > i \{ display: block !important;/);
assert.match(css,/:is\(#profileInlineNationality,#profileInlineBirthCountry,#profileInlineCity,#profileInlineCountryResidence,#profileInlineCompany,#profileInlineTimezone\) \{/);
assert.match(css,/\.profile-nationality-select \.atsrs-select-trigger/);
assert.match(css,/\.profile-nationality-select \.atsrs-disclosure-indicator/);
assert.match(css,/\.profile-nationality-select > \.profile-nationality-caret/);
assert.match(css,/\.profile-nationality-select > \.atsrs-disclosure-shell[\s\S]*?height:100% !important/);
assert.match(css,/\.profile-nationality-select \.atsrs-disclosure-shell \{\s*position: absolute !important; inset: 0 !important/);
assert.match(css,/#profileInlineNationalityValue/);
assert.match(js,/function finishPersonal\(\)\{var savedX=window\.scrollX,savedY=window\.scrollY/);
assert.match(js,/function setPersonalControls\(enabled\)/);
assert.doesNotMatch(js,/read\.classList\.(?:add|remove)\('hidden'\)/);
assert.match(js,/shell\.replaceWith\(control\)/);
assert.match(css,/profile-inline-editing #profilePersonalReadView \.profile-inline-input-controlled > strong \{[\s\S]*?display:none !important/);
assert.match(css,/#profilePersonalReadView \.profile-inline-input-controlled > \.profile-inline-control:is\(:focus,:focus-visible\) \{[\s\S]*?outline:0 !important/);
assert.match(js,/summaryEdit\.focus\(\{preventScroll:true\}\)/);
assert.match(js,/window\.scrollTo\(savedX,savedY\)/);
assert.match(css,/overflow-anchor:none !important/);
assert.match(js,/birthPicker\.dataset\.atsrsDatePosition='anchor-above-right'/);
assert.match(js,/birthPicker\.dataset\.atsrsDateAnchorId='profileInlineBirthDateDisplay'/);
assert.match(datePicker,/activeInput\.dataset\.atsrsDatePosition==='anchor-above-right'/);
assert.match(datePicker,/anchorRect\.right-anchoredDialogRect\.width/);
assert.match(datePicker,/anchorRect\.top-anchoredDialogRect\.height-6/);
assert.match(js,/function bindPersonalActions\(\)/);
assert.doesNotMatch(js,/Save Changes/);
assert.equal((html.match(/id="profileSummaryEditBtn"/g)||[]).length,1);
assert.equal((html.match(/id="profileInlineSaveBtn"/g)||[]).length,1);
assert.equal((html.match(/id="profileInlineCancelBtn"/g)||[]).length,1);
assert.equal((html.match(/id="profileStageAvailabilityEditBtn"/g)||[]).length,1);
assert.equal((html.match(/id="profileAvailabilitySaveBtn"/g)||[]).length,1);
assert.equal((html.match(/id="profileAvailabilityCancelBtn"/g)||[]).length,1);
assert.doesNotMatch(html,/id="profileStageAvailabilityConfirmed"/);
assert.doesNotMatch(html,/>Edit availability<\/button>/);
assert.match(html,/class="profile-availability-actions"[\s\S]*?aria-label="Save work availability changes"[\s\S]*?aria-label="Cancel work availability changes"[\s\S]*?aria-label="Edit work availability"/);
assert.match(js,/function bindAvailabilityActions\(\)/);
assert.match(js,/\['setup2faBtn','viewSessionsBtn'\]\.forEach/);
assert.match(js,/moveRow\('deleteAccountBtn','profileSecurityControls'\)/);
assert.match(html,/id="profileSecurityControls" class="profile-settings-list profile-security-grid"[\s\S]*?<\/div>\s*<\/div>\s*<\/section>\s*<div id="profileSecurityCodeModal"/);
assert.match(html,/id="profileSecurityVerificationResult" class="profile-security-verification-result"/);
assert.match(js,/openSecurityCodeModal\(\)/);
assert.match(js,/closeSecurityCodeModal\(\)/);
assert.doesNotMatch(html,/Manage your account security and access settings\./);
assert.doesNotMatch(js,/\['setup2faBtn','viewSessionsBtn','profileTimezone','manageNotifyBtn','deleteAccountBtn'\]/);
assert.match(js,/function decorateSecurityControls\(\)/);
assert.match(js,/function openSecurityContactEditor\(kind,trigger\)/);
assert.match(js,/window\.saveProfile\(\{contactChanged:whatsapp\?'whatsapp':'mobile'\}\)/);
assert.doesNotMatch(js,/data-profile-stage-edit[\s\S]{0,220}enterPersonal/);
assert.match(js,/function bindSecurityVerification\(\)/);
assert.match(dashboard,/window\.atsrsContactVerification=/);
assert.match(html,/id="profileSecurityVerification"/);
assert.match(html,/id="profileSecuritySendCode"/);
assert.match(html,/class="profile-security-code"/);
assert.match(dashboard,/existingPhone=String\(existing\.phone\|\|\(\(existing\.phoneCountryCode\|\|''\)\+\(existing\.phoneLocal\|\|''\)\)\)/);
assert.match(dashboard,/phoneVerified:options\.contactChanged==='mobile'&&existingPhone!==phoneParts\.full\?false/);
assert.match(dashboard,/whatsappVerified:options\.contactChanged==='whatsapp'&&existingWhatsapp!==whatsappParts\.full\?false/);
assert.match(css,/\.profile-security-contact-editor \{ margin-top:10px/);
assert.doesNotMatch(css,/\.profile-security-contact-editor \{ position:fixed/);
assert.match(html,/css\/profile-production-parity-v5878\.css\?v=5990/);
assert.match(html,/js\/profile-workspace-v5886\.js\?v=5960/);
assert.match(html,/id="profileStageCity"/);
assert.match(html,/id="profileStageTimezone"/);
assert.match(html,/id="profileSecurityContactSource"/);
assert.match(js,/bindSecurityVerification\(\)/);
assert.match(css,/\.profile-calendar-card \{ display:none !important; \}/);
assert.match(css,/\.profile-information-grid \{ grid-template-columns:repeat\(8,minmax\(0,1fr\)\); \}/);
assert.match(js,/decorateSecurityCard\('setup2faBtn','ph-lock-key'/);
assert.match(js,/decorateSecurityCard\('viewSessionsBtn','ph-monitor'/);
assert.match(js,/decorateSecurityCard\('deleteAccountBtn','ph-trash'/);
assert.match(css,/@media \(min-width:761px\) \{[\s\S]*?\.profile-security-verification-flow \{[\s\S]*?grid-template-columns:repeat\(3,minmax\(0,1fr\)\);[\s\S]*?grid-template-rows:minmax\(0,1fr\) 62px;/);
assert.match(html,/class="profile-security-send-inline"[\s\S]*?id="profileSecuritySendCode"/);
assert.match(html,/profile-security-step-send/);
assert.match(html,/>Choose channel</);
assert.match(css,/\.profile-security-grid \{ grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);
assert.match(css,/\.profile-security-grid \.profile-security-card\.is-danger \{ grid-column:auto/);
assert.match(js,/profileAvailabilityInlineActions/);
assert.match(js,/function buildAvailabilityEditor\(\)/);
assert.match(js,/profileInlineAvailabilityStatus/);
assert.match(js,/profileInlineAvailableFrom/);
assert.match(js,/function availabilityDateText\(value\)/);
assert.match(js,/date\.addEventListener\('change'/);
assert.doesNotMatch(html,/ph-calendar-blank profile-availability-read-value/);
assert.match(css,/dd:has\(#profileInlineAvailableFrom\)[\s\S]*?\.atsrs-date-input \{[\s\S]*?opacity:0 !important/);
assert.match(js,/profileInlineWorkPreference/);
assert.match(js,/profileInlineAvailabilityNoticePeriod/);
assert.match(js,/function setInlineSelectValue\(select,value\)/);
assert.match(js,/async function refreshAvailabilityEditor\(\)\{if\(window\.loadProfile\)await Promise\.resolve\(window\.loadProfile\(\)\);syncAvailabilityEditor\(\)\}/);
assert.match(js,/async function enterAvailability\(\)/);
assert.doesNotMatch(js,/focusTarget=first/);
assert.match(css,/#profilePersonalReadView \.profile-information-field:hover:not\(:focus-within\)/);
assert.match(css,/\.profile-availability-fields dd:hover:not\(:focus-within\)/);
assert.match(js,/async function cancelAvailability\(\)\{await refreshAvailabilityEditor\(\);finishAvailability\(\)\}/);
assert.doesNotMatch(js,/availabilityCard\.appendChild\(availability\)/);
assert.match(css,/\.profile-availability-actions \{[\s\S]*?height:30px/);
assert.match(css,/\.profile-availability-card\.is-editing \.profile-availability-read-value \{[\s\S]*?display:flex !important;[\s\S]*?pointer-events:none/);
assert.match(css,/dd:has\(#profileInlineAvailabilityNoticePeriod\) \.profile-availability-read-value \{[\s\S]*?display:none !important/);
assert.match(css,/\.profile-availability-card\.is-editing[\s\S]*?\.atsrs-select-trigger,\.atsrs-date-input\)[\s\S]*?color:transparent !important; caret-color:transparent !important/);
assert.match(css,/\.profile-availability-inline-control\.atsrs-select-source \{[\s\S]*?display:none !important/);
assert.match(css,/\.atsrs-disclosure-shell > \.atsrs-disclosure-indicator \{[\s\S]*?opacity:0 !important/);
assert.match(css,/\.profile-availability-card\.is-editing \.profile-availability-fields > div:focus-within dt \{[\s\S]*?var\(--atsrs-field-accent/);
assert.match(css,/\.profile-availability-card\.is-editing \.profile-availability-fields > div:focus-within dd \{[\s\S]*?background:var\(--surface-2\) !important/);
assert.match(css,/\.profile-availability-card:not\(\.is-editing\) \.profile-availability-fields dd > \.atsrs-disclosure-shell \{[\s\S]*?display:none !important/);
assert.match(css,/#profileInlineAvailabilityNoticePeriod \{[\s\S]*?height:20px !important;[\s\S]*?border:0 !important/);
assert.match(html,/id="profileTabPersonalPanel"[\s\S]*?class="profile-information-actions"[\s\S]*?aria-label="Save profile changes"[\s\S]*?aria-label="Cancel profile changes"[\s\S]*?aria-label="Edit profile"/);
assert.match(html,/id="profileSummaryEditBtn"[\s\S]*?<svg viewBox="0 0 32 32"/);
assert.doesNotMatch(html,/id="profileSummaryEditBtn"[^>]*>[\s\S]{0,100}Edit profile<\/button>/);
assert.doesNotMatch(dashboard,/closest\('#profileSummaryEditBtn'\)[\s\S]{0,300}edit\.click\(\)/);
assert.match(dashboard,/window\.saveProfile=async function\(options\)/);
assert.match(dashboard,/window\.atsrsIdentityVerification/);
assert.doesNotMatch(dashboard,/identity\\s\*card\|id\\s\*card/);
assert.match(css,/\.profile-settings-viewport \{[\s\S]+height: 294px/);
assert.match(css,/\.profile-settings-panel\[hidden\] \{ display: none !important; \}/);
assert.match(css,/#profileTabSharingPanel[\s\S]+background: var\(--surface, #0b0d0d\) !important/);
assert.doesNotMatch(html,/id="profileTabSharingPanel"[^>]*>[\s\S]{0,80}<h4>Sharing<\/h4>/);
assert.match(css,/#profileSharingControls :is\(\.sharing-heading,#shareSub\) \{ display:none !important; \}/);
assert.match(css,/#profileSharingControls > #shareProfilePanel \{ display:none !important; \}/);
assert.match(css,/#profileTabSharingPanel \{ box-sizing:border-box !important; height:100% !important; max-height:100% !important; \}/);
assert.match(css,/profile-inline-grid #inlineCountryValue \{[\s\S]*?font-size: 12px !important;[\s\S]*?font-weight: 500 !important;/);
assert.match(css,/#profileTabPersonalPanel > \.profile-information-actions \{[\s\S]*?position:absolute !important;[\s\S]*?top:12px !important;[\s\S]*?right:18px !important;/);
assert.match(css,/\.profile-information-action \{[\s\S]*?width:30px !important;[\s\S]*?height:30px !important;/);
assert.match(css,/\.profile-information-field:focus-within > span,[\s\S]*?color: var\(--atsrs-field-accent\) !important;/);
assert.match(css,/profile-inline-editing \.profile-inline-grid :is\(\.profile-information-field,\.profile-information-contact\):focus-within,[\s\S]*?border-color:var\(--atsrs-field-focus-block-line\) var\(--atsrs-field-focus-inline-line\) !important;[\s\S]*?box-shadow:var\(--atsrs-field-focus-shadow\) !important;/);
assert.match(css,/html\[data-theme="dark"\][\s\S]*?:-webkit-autofill[\s\S]*?color-mix\(in srgb,var\(--accent\) 9%,var\(--surface-2\)\)/);
assert.match(css,/html\[data-theme="light"\][\s\S]*?:-webkit-autofill[\s\S]*?color-mix\(in srgb,var\(--accent\) 6%,#fff\)/);
assert.match(css,/html\[data-theme="light"\][\s\S]*?\.profile-availability-actions \.profile-information-action,[\s\S]*?#profileTabPersonalPanel#profileTabPersonalPanel \.profile-information-action \{[\s\S]*?color:var\(--atsrs-shell-accent-strong,#245b93\) !important/);
assert.doesNotMatch(css,/\.profile-summary-edit/);
console.log('Personal Profile workspace V5886 contracts passed');
