const assert=require('node:assert/strict');
const fs=require('node:fs');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('css/profile-sharing-v1.css','utf8');
const js=fs.readFileSync('js/profile-sharing-v1.js','utf8');

assert.match(html,/id="profileSharingV1"/);
['anyone','recruiters','recipient'].forEach(value=>assert.match(html,new RegExp(`name="profileSharingAudience" value="${value}"`)));
['24h','3d','7d','custom'].forEach(value=>assert.match(html,new RegExp(`name="profileSharingExpiry" value="${value}"`)));
assert.match(html,/id="profileSharingCustomExpiry" type="date"/);
assert.match(html,/id="profileSharingActiveList"/);
assert.match(html,/id="profileSharingCreateBtn"/);
assert.match(html,/id="profileSharingDocumentDialog"/);
assert.match(html,/id="profileSharingDocumentChoices"/);
assert.doesNotMatch(html,/id="profileSharingV1"[\s\S]*?<h[1-6][^>]*>Sharing<\/h[1-6]>/);
assert.doesNotMatch(html,/id="profileSharingV1"[\s\S]*?Create share links to let others/);
assert.doesNotMatch(html,/id="profileSharingV1"[\s\S]*?Create Share Link/);
assert.match(css,/profile-sharing-v1\{[^}]*height:100%/);
assert.match(css,/grid-template-rows:108px minmax\(0,1fr\)/);
assert.match(css,/profile-sharing-setup\{[^}]*padding:0;[^}]*border:0;[^}]*background:transparent/);
assert.doesNotMatch(css,/:is\(\.profile-sharing-setup,\.profile-sharing-audience-grid/);
assert.match(css,/@media\(max-width:760px\)/);
assert.match(js,/window\.copyShareLink/);
assert.match(js,/window\.previewShareProfile/);
assert.match(js,/window\.revokeShareProfileLink/);
assert.match(html,/css\/profile-sharing-v1\.css\?v=9/);
assert.match(css,/profile-sharing-expiry-check/);
assert.match(css,/profile-sharing-v1 \*\{box-sizing:border-box\}/);
assert.match(css,/profile-sharing-expiry-options label\.is-selected \.profile-sharing-expiry-check/);
assert.match(css,/profile-sharing-audience-grid label\.is-selected/);
assert.doesNotMatch(css,/profile-sharing-audience-grid label:has\(input:checked\)/);
assert.match(css,/profile-sharing-expiry-check\{[^}]*box-shadow/);
assert.match(css,/grid-template-columns:repeat\(3,minmax\(0,150px\)\)/);
assert.doesNotMatch(html,/Information included/);
assert.doesNotMatch(html,/View details/);
assert.match(js,/syncCustomDate\(\)/);
assert.match(html,/js\/profile-sharing-v1\.js\?v=8/);
assert.match(html,/id="profileSharingSaveBtn"[\s\S]*?id="profileSharingCancelBtn"[\s\S]*?id="profileSharingEditBtn"/);
assert.match(js,/SHARING_SETUP_STORAGE_KEY='atsrs_profile_sharing_setup'/);
assert.match(js,/SHARING_SETUP_METADATA_KEY='atsrs_profile_sharing_setup'/);
assert.match(js,/auth\.updateUser\(\{data:\{atsrs_profile_sharing_setup:value\}\}\)/);
assert.match(js,/auth\.getUser\(\)/);
assert.match(js,/window\.addEventListener\('focus'/);
assert.match(js,/atsrs:cloud-data-loaded'[\s\S]*?refreshServerSetup\(true\)/);
assert.match(js,/function setEditing\(value\)/);
assert.match(js,/applySetup\(savedSetup\);setEditing\(false\)/);
assert.match(js,/dataset\.wasChecked==='true'/);
assert.match(js,/label\.addEventListener\('pointerdown'/);
assert.match(js,/atsrsPrepareProfileShare/);
assert.match(js,/dialog\.showModal\(\)/);
assert.match(js,/create\.disabled=editing/);
assert.match(css,/profile-sharing-document-dialog::backdrop/);
assert.match(css,/profile-sharing-create-button/);
assert.match(css,/profile-sharing-v1:not\(\.is-editing\) \.profile-sharing-setup\{pointer-events:none\}/);
console.log('Profile Sharing V1 contracts passed');
