const assert=require('node:assert/strict');
const fs=require('node:fs');
const html=fs.readFileSync('index.html','utf8');
const js=fs.readFileSync('js/profile-workspace-v5886.js','utf8');
const dashboard=fs.readFileSync('js/dashboard.js','utf8');
const datePicker=fs.readFileSync('js/date-picker.js','utf8');
const css=fs.readFileSync('css/profile-production-parity-v5878.css','utf8');

['Personal','Privacy','Sharing','Security'].forEach(name=>{
  assert.match(html,new RegExp(`id="profileTab${name}Btn"[^>]+aria-controls="profileTab${name}Panel"`));
  assert.match(html,new RegExp(`id="profileTab${name}Panel"[^>]+role="tabpanel"[^>]+aria-labelledby="profileTab${name}Btn"`));
});
assert.doesNotMatch(html,/profileTab(?:Privacy|Sharing|Security)Btn[^>]+aria-disabled/);
assert.match(js,/event\.key==='ArrowRight'\|\|event\.key==='ArrowLeft'/);
assert.match(js,/Discard unsaved profile changes/);
assert.match(js,/nationality=document\.createElement\('select'\)/);
assert.match(js,/nationality\.appendChild\(option\.cloneNode\(true\)\)/);
assert.doesNotMatch(js,/nationality\.addEventListener\('change'/);
assert.match(dashboard,/nationality:val\('profileInlineNationality'\)\|\|existing\.nationality\|\|val\('profileCountry'\)/);
assert.match(dashboard,/setVal\('profileInlineNationality',p\.nationality\|\|p\.country\)/);
assert.match(dashboard,/\['profileStageNationality',p\.nationality\|\|p\.country\]/);
assert.match(css,/\.profile-nationality-select > i \{ display: block !important;/);
assert.match(js,/function finishPersonal\(\)\{var savedX=window\.scrollX,savedY=window\.scrollY/);
assert.match(js,/summaryEdit\.focus\(\{preventScroll:true\}\)/);
assert.match(js,/setTimeout\(function\(\)\{window\.scrollTo\(savedX,savedY\)\},0\)/);
assert.match(js,/birthPicker\.dataset\.atsrsDatePosition='anchor-above-right'/);
assert.match(js,/birthPicker\.dataset\.atsrsDateAnchorId='profileInlineBirthDateDisplay'/);
assert.match(datePicker,/activeInput\.dataset\.atsrsDatePosition==='anchor-above-right'/);
assert.match(datePicker,/anchorRect\.right-anchoredDialogRect\.width/);
assert.match(datePicker,/anchorRect\.top-anchoredDialogRect\.height-6/);
assert.match(js,/function bindPersonalActions\(\)/);
assert.doesNotMatch(js,/Save Changes/);
assert.equal((html.match(/id="profileSummaryEditBtn"/g)||[]).length,1);
assert.equal((html.match(/id="profileInlineSaveBtn"/g)||[]).length,1);
assert.equal((html.match(/id="profileInlineCancelBtn"/g)||[]).length,1);
assert.match(html,/id="profileTabPersonalPanel"[\s\S]*?class="profile-information-actions"[\s\S]*?aria-label="Save profile changes"[\s\S]*?aria-label="Cancel profile changes"[\s\S]*?aria-label="Edit profile"/);
assert.match(html,/id="profileSummaryEditBtn"[\s\S]*?<svg viewBox="0 0 32 32"/);
assert.doesNotMatch(html,/id="profileSummaryEditBtn"[^>]*>[\s\S]{0,100}Edit profile<\/button>/);
assert.doesNotMatch(dashboard,/closest\('#profileSummaryEditBtn'\)[\s\S]{0,300}edit\.click\(\)/);
assert.match(dashboard,/window\.saveProfile=async function\(options\)/);
assert.match(dashboard,/window\.atsrsIdentityVerification/);
assert.doesNotMatch(dashboard,/identity\\s\*card\|id\\s\*card/);
assert.match(css,/\.profile-settings-viewport \{[\s\S]+height: 294px/);
assert.match(css,/\.profile-settings-panel\[hidden\] \{ display: none !important; \}/);
assert.match(css,/#profileTabSharingPanel[\s\S]+background: var\(--surface, #0b0d0d\) !important/);
assert.match(css,/profile-inline-grid #inlineCountryValue \{[\s\S]*?font-size: 12px !important;[\s\S]*?font-weight: 500 !important;/);
assert.match(css,/#profileTabPersonalPanel > \.profile-information-actions \{[\s\S]*?position:absolute !important;[\s\S]*?top:12px !important;[\s\S]*?right:18px !important;/);
assert.match(css,/\.profile-information-action \{[\s\S]*?width:30px !important;[\s\S]*?height:30px !important;/);
assert.match(css,/\.profile-information-field:focus-within > span,[\s\S]*?color: var\(--accent\) !important;/);
assert.match(css,/html\[data-theme="dark"\][\s\S]*?:-webkit-autofill[\s\S]*?color-mix\(in srgb,var\(--accent\) 9%,var\(--surface-2\)\)/);
assert.match(css,/html\[data-theme="light"\][\s\S]*?:-webkit-autofill[\s\S]*?color-mix\(in srgb,var\(--accent\) 6%,#fff\)/);
assert.doesNotMatch(css,/\.profile-summary-edit/);
console.log('Personal Profile workspace V5886 contracts passed');
