const assert=require('node:assert/strict');
const fs=require('node:fs');
const html=fs.readFileSync('index.html','utf8');
const js=fs.readFileSync('js/profile-privacy-v1.js','utf8');
const css=fs.readFileSync('css/profile-privacy-v1.css','utf8');

['public','custom','private'].forEach(mode=>assert.match(html,new RegExp(`name="profilePrivacyMode" value="${mode}"`)));
['phone','email','location','availability','position','salary','birthDate','about'].forEach(field=>assert.match(js,new RegExp(`key:'${field}'`)));
assert.doesNotMatch(html,/id="profilePrivacyAudience"/);
assert.doesNotMatch(html,/id="profilePrivacyVisibilityTitle"/);
assert.doesNotMatch(html,/class="profile-privacy-heading"/);
assert.doesNotMatch(html,/id="profilePrivacyInformationTitle"/);
assert.doesNotMatch(html,/Information Visibility/);
assert.match(html,/id="profilePrivacyRows"/);
assert.doesNotMatch(html,/id="profilePrivacyResetBtn"/);
assert.doesNotMatch(html,/id="profilePrivacySaveBtn"/);
assert.match(js,/privacySettings=clone\(draft\)/);
assert.match(js,/function scheduleSave\(\)/);
assert.match(js,/window\.atsrsCloudData\.flush/);
assert.match(js,/mode==='public'\?'Public':mode==='private'\?'Private':'Link Only'/);
assert.match(css,/:has\(#profileTabPrivacyPanel\.is-active\)/);
assert.match(css,/@media\(max-width:620px\)/);
assert.match(css,/profile-privacy-mode-card\{[^}]*min-height:64px;[^}]*padding:7px 14px/);
assert.match(html,/css\/profile-privacy-v1\.css\?v=7/);
assert.match(html,/js\/profile-privacy-v1\.js\?v=2/);
console.log('Profile Privacy V1 contracts passed');
