const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'css', 'public-landing.css'), 'utf8');
const js = fs.readFileSync(path.join(root, 'js', 'public-landing.js'), 'utf8');
const storage = fs.readFileSync(path.join(root, 'js', 'storage.js'), 'utf8');

assert.ok(index.indexOf('id="landingPage"') < index.indexOf('id="auth"'), 'public landing must precede auth');
assert.match(index, /<template id="sharedProfileTemplate">[\s\S]*?<section id="sharedProfilePage" class="shared-profile-page hidden"/);
assert.doesNotMatch(index, /<main id="sharedProfilePage"/);
assert.match(index, /window\.atsrsMountSharedProfile=function\(\)[\s\S]*?template\.content\.cloneNode\(true\)/);
assert.match(index, /if\(window\.__atsrsEntryRoute==='share'\)window\.atsrsMountSharedProfile\(\)/);
assert.match(index, /href="\?view=login"[^>]*>Log in</);
assert.match(index, /href="\?view=signup"/);
assert.match(index, /class="public-audience-grid public-job-search-grid"[\s\S]*?>JOB SEARCH<[\s\S]*?<h3>Find your next opportunity<\/h3>/);
assert.match(index, /Discover recruiter-sourced opportunities across multiple industries, locations and work types\./);
assert.match(index, /href="\?view=jobs">Explore Jobs/);
assert.equal((index.match(/id="jobsPage"/g) || []).length, 1, 'Home CTA must reuse the existing Jobs page');
assert.match(index, /class="public-home-link" href="#top" aria-label="Home"/);
assert.match(index, /class="public-home-link public-home-mobile" href="#top" aria-label="Home"/);
assert.match(index, /window\.__atsrsEntryRoute=atsrsEntryCallback\?'callback'/);
assert.match(index, /window\.__atsrsSuppressAutomaticSessionOpen=[\s\S]*?window\.__atsrsEntryRoute==='auth'\|\|window\.__atsrsEntryRoute==='share'/);
assert.match(storage, /window\.__atsrsSuppressAutomaticSessionOpen[\s\S]*?event==='INITIAL_SESSION'[\s\S]*?event==='TOKEN_REFRESHED'[\s\S]*?event==='getSession'/);
assert.match(storage, /event==='SIGNED_IN'&&window\.__atsrsEntryRoute!=='auth'/);
assert.match(index, /data-public-theme-toggle role="switch"/);
assert.match(index, /public-theme-track/);
assert.match(index, /public-theme-thumb/);
for (const plan of ['FREE', 'BRONZE', 'SILVER', 'GOLD']) assert.match(index, new RegExp(`>${plan}<`));
assert.match(index, /public-plan-name">FREE[\s\S]*?href="\?view=signup">Start with Free<\/a>/);
for (const plan of ['bronze', 'silver', 'gold']) assert.match(index, new RegExp(`href="pricing\\.html#${plan}">View plan details</a>`));
assert.match(index, /1 lifetime AI scan/);
assert.match(index, /No Candidate directory listing/);
assert.match(index, /No SMS or WhatsApp credits/);
assert.match(index, /Candidate directory visibility/);
assert.doesNotMatch(index, /end-to-end encryption|mobile app|Google Calendar integration/i);
assert.doesNotMatch(index, /\$\d+|€\d+|£\d+/);
assert.match(js, /setInterval\(rotateWordmarks,10000\)/);
assert.match(js, /if\(callback\|\|publicShare\)return;[\s\S]*?atsrsGetSessionSingleFlight[\s\S]*?session&&session\.user[\s\S]*?atsrsResumeSession\(session,'resume'\)[\s\S]*?showLanding\(\)/);
assert.match(js, /client\.auth\.getSession\(\)/);
assert.match(js, /requestedJobs=requestedView==='jobs'/);
assert.match(js, /if\(requestedJobs\)[\s\S]*?localStorage\.setItem\('atsrs_current_page','jobs'\)/);
assert.match(js, /if\(requestedJobs\)showExistingAuth\('login'\)/);
assert.match(js, /function removeSharedProfile\(\)[\s\S]*?sharedProfile\.remove\(\)/);
assert.match(js, /function showLanding\(\)[\s\S]*?removeSharedProfile\(\)/);
assert.match(js, /function showExistingAuth\(view\)[\s\S]*?removeSharedProfile\(\)/);
assert.match(js, /swap\.classList\.toggle\('show-amp'\)/);
assert.match(js, /letterS\.textContent='S'/);
assert.match(js, /ampersand\.textContent='&'/);
assert.match(js, /prefix\.className='atsrs-brand-prefix'/);
assert.match(js, /suffix\.className='atsrs-brand-suffix'/);
assert.match(js, /prefers-reduced-motion: reduce/);
assert.match(css, /\.atsrs-brand-swap\.show-amp \.atsrs-brand-s/);
assert.match(css, /\.atsrs-brand-swap\.show-amp \.atsrs-brand-amp/);
assert.match(css, /rotateY\(-?88deg\)/);
assert.doesNotMatch(css, /\.atsrs-brand-s\{[^\n]*transform:rotate\(/);
assert.doesNotMatch(css, /\.atsrs-brand-amp\{[^\n]*transform:rotate\(/);
assert.match(css, /Applicant Tracking System & Recruitment Solutions/);
assert.match(js, /authSubtitle\.textContent='Applicant Tracking System & Recruitment Solutions'/);
assert.match(css, /font:700 9px\/1\.25/);
assert.match(css, /font-size:7\.5px/);
assert.match(storage, /window\.__atsrsSuppressAutomaticSessionOpen=true;[\s\S]*?window\.location\.replace\(window\.location\.pathname\)/);
assert.doesNotMatch(css, /\.public-theme-toggle:hover \.public-theme-track\{[\s\S]*?(?:background|border-color):/);
assert.doesNotMatch(css, /Automated Reporting & Tracking System/);
assert.doesNotMatch(js, /Automated Reporting & Tracking System/);
assert.doesNotMatch(js, /keepProductName|setTimeout\(keepProductName/);
assert.match(js, /aria-checked/);
assert.doesNotMatch(js, /button\.innerHTML/);
assert.match(css, /@media\(max-width:420px\)/);
assert.match(css, /\.public-home-link\{width:44px;min-width:44px;height:44px/);
assert.match(css, /@media\(max-width:1050px\)\{[\s\S]*?\.public-home-mobile\{display:inline-flex\}/);
assert.match(css, /overflow-x:clip/);
assert.match(css, /html:has\(body > \.atsrs-public-landing:not\(\.hidden\)\)[\s\S]*?overflow-y:auto!important/);
assert.match(css, /body:has\(> \.atsrs-public-landing:not\(\.hidden\)\)[\s\S]*?overflow-y:visible!important/);
assert.match(css, /touch-action:pan-y/);
assert.match(css, /body\.atsrs-public-view > #auth,[\s\S]*?body\.atsrs-public-view > #app\{display:none!important\}/);
assert.match(css, /body\.auth-open:has\(> #auth:not\(\.hidden\)\)\{[\s\S]*?overflow:hidden!important\}/);
assert.match(css, /body\.auth-open > #auth:not\(\.hidden\)[\s\S]*?overflow:hidden!important/);
assert.match(js, /function unlockPublicScroll\(\)[\s\S]*?style\.removeProperty\(property\)[\s\S]*?classList\.remove\('auth-open','app-open'/);
assert.match(js, /function showLanding\(\)[\s\S]*?unlockPublicScroll\(\)/);
assert.match(css, /html\[data-theme\] body \.atsrs-public-landing \.public-theme-toggle:hover,[\s\S]*?background:transparent!important/);
assert.match(css, /\.public-theme-toggle::before,[\s\S]*?\.public-theme-toggle::after\{display:none!important;content:none!important\}/);
assert.match(index, /href="data-protection\.html">Data Protection &amp; GDPR<\/a>/);
assert.match(index, /href="terms\.html">Terms of Use<\/a>/);
assert.match(index, /href="privacy\.html">Privacy Notice<\/a>/);
assert.match(index, /href="data-deletion\.html">Data Rights<\/a>/);
assert.match(index, /href="security\.html">Report a Security Issue<\/a>/);
assert.doesNotMatch(index, /class="public-footer-primary"/);
assert.doesNotMatch(index, /class="public-footer-brand"/);
assert.match(index, /class="public-footer-legal"[\s\S]*?Data Protection &amp; GDPR[\s\S]*?Data Rights<\/a><\/nav>[\s\S]*?class="public-footer-bottom"/);
assert.match(css, /\.public-footer\{display:grid;grid-template-columns:1fr;[\s\S]*?align-items:start/);
assert.match(css, /\.public-footer-legal\{[\s\S]*?justify-content:center/);
assert.match(css, /\.public-job-search-grid article\{grid-column:2\}/);
assert.match(css, /@media\(max-width:1050px\)\{[\s\S]*?\.public-job-search-grid\{[^}]*grid-template-columns:minmax\(0,1fr\)[^}]*\}[\s\S]*?\.public-job-search-grid article\{grid-column:auto\}/);

for (const image of ['personal-dashboard.png', 'candidate-directory.png', 'corporate-personnel.png']) {
  assert.ok(fs.existsSync(path.join(root, 'assets', 'landing', image)), `${image} must exist`);
}

console.log('Public landing and animated wordmark contract tests passed');
