const assert=require('node:assert/strict');
const fs=require('node:fs');

const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('css/recruiter-directory-v6029.css','utf8');
const js=fs.readFileSync('js/recruiters.js','utf8');

assert.match(html,/css\/recruiter-directory-v6029\.css\?v=6041/);
assert.match(css,/body:where\(\.personal-mode,\.company-mode\).*\.employer-action-linkedin,\.employer-action-jobs,\.employer-action-share/);
assert.match(css,/max-height:32px !important/);
assert.match(html,/js\/recruiters\.js\?v=6040/);
assert.match(html,/class="employers-hero recruiters-hero"/);
assert.match(html,/Global recruiter network/);
assert.match(html,/id="recruitersExploreAll"/);
assert.match(html,/id="recruitersExploreAllLabel"/);
assert.match(html,/id="recruitersActiveVacancies"/);
assert.doesNotMatch(html,/id="recruitersCompanyCount"/);
assert.match(html,/class="recruiters-trust-strip"/);
assert.match(html,/LinkedIn verified/);
assert.match(html,/Vacancies linked/);
assert.match(html,/Profile sharing controlled/);
assert.match(html,/id="recruitersPaginationTop"[^>]*data-recruiters-pagination/);
assert.match(html,/id="recruitersPaginationBottom"[^>]*data-recruiters-pagination/);
assert.match(css,/body:has\(#recruitersPage:not\(\.hidden\)\)[\s\S]*?#pageTitle \{[\s\S]*?display:none !important;/);
assert.match(css,/#recruitersPage\.employers-page \{[\s\S]*?width:min\(100%,1440px\);/);
assert.match(css,/\.recruiters-hero \{[\s\S]*?margin:8px 0 10px;/);
assert.match(css,/recruiter-directory-orbit-v1\.png/);
assert.match(css,/#recruitersPage \.recruiters-trust-strip \{/);
assert.match(css,/#recruitersPage \.employers-grid \{[\s\S]*?grid-template-columns:repeat\(3,minmax\(0,1fr\)\);/);
assert.match(css,/#recruitersPage \.employer-card \{[\s\S]*?height:auto;[\s\S]*?min-height:172px;/);
assert.match(css,/#recruitersPage \.employer-actions \{[\s\S]*?display:flex;[\s\S]*?flex-wrap:nowrap;/);
assert.match(css,/#recruitersPage \.employer-actions a,[\s\S]*?flex:1 1 0;[\s\S]*?height:32px !important;[\s\S]*?font-size:9px;/);
assert.match(css,/#recruitersPage \.recruiters-trust-strip \{[\s\S]*?background:transparent;[\s\S]*?backdrop-filter:none;/);
assert.match(css,/#recruitersPage \.recruiters-pagination \{/);
assert.match(js,/function resetFilters\(activeOnly\)/);
assert.match(js,/recruitersExploreAll/);
assert.match(js,/"Explore all " \+ recruiters\.length/);
assert.match(js,/recruitersActiveVacancies/);
assert.match(js,/RECRUITER_PAGE_SIZE = 30/);
assert.match(js,/function renderPagination\(pageCount\)/);
assert.match(js,/recruitersShown \+ " of " \+ visible\.length \+ " recruiters"/);
assert.doesNotMatch(js,/companyCount \+ " companies"/);
assert.match(js,/querySelectorAll\("\[data-recruiters-pagination\]"\)/);
assert.match(js,/summary\.title = summary\.textContent/);
assert.match(js,/jobsAction\.setAttribute\("aria-label", "View offers on ATSRS"\)/);

console.log('Recruiter Directory V6029 contracts passed');
