const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=(file)=>fs.readFileSync(path.join(root,file),'utf8');
const index=read('index.html');
const css=read('css/workspace-card-glass-v529.css');
const harness=read('tests/fixtures/workspace-card-glass-v529-qa.html');

assert.match(index,/data-atsrs-build="V530"/);
assert.doesNotMatch(index,/workspace-card-glass-v529\.css\?v=529/);
assert.match(css,/--atsrs-v529-light-bg-top:#ccd3de/);
assert.match(css,/--atsrs-v529-light-bg-bottom:#bac9d9/);
assert.match(css,/--atsrs-v529-dark-bg-top:#151d2a/);
assert.match(css,/--atsrs-v529-dark-bg-bottom:#040a14/);
assert.match(css,/--atsrs-v529-light-top:rgba\(189,203,220,\.62\)/);
assert.match(css,/--atsrs-v529-light-bottom:rgba\(202,214,229,\.46\)/);
assert.match(css,/--atsrs-v529-dark-top:rgba\(23,31,46,\.56\)/);
assert.match(css,/--atsrs-v529-dark-bottom:rgba\(11,18,30,\.44\)/);
assert.match(css,/#dashboardPage#dashboardPage \.dashboard-priority-alerts-panel/);
assert.match(css,/#dashboardPage#dashboardPage \.talent-messages-panel/);
assert.match(css,/#profilePage#profilePage \.work-availability-card/);
assert.match(css,/#refsPage#refsPage \.atsrs-v156-main-box/);
assert.match(css,/#introPage#introPage \.roadmap-card/);
assert.match(css,/#projectsPage#projectsPage \.project-workspace-card/);
assert.match(css,/#personnelPage#personnelPage \.linked-personnel-card/);
assert.match(css,/#candidatesPage#candidatesPage \.talent-card/);
assert.match(css,/#compliancePage#compliancePage \.corporate-compliance-card/);
assert.doesNotMatch(css,/input:not/);
assert.doesNotMatch(css,/\.sidebar/);
assert.doesNotMatch(css,/#landingPage/);
assert.doesNotMatch(css,/#login/);
assert.match(css,/> \.main\{/);
assert.match(harness,/workspace-card-glass-v529\.css\?v=529/);
assert.match(harness,/dashboard-priority-alerts-panel/);
assert.match(harness,/work-availability-card/);
assert.match(harness,/atsrs-v156-main-box/);
assert.match(harness,/roadmap-card/);

console.log('V529 complete workspace card material contracts passed');
